import type { NewModelConfig } from "../schema";

export const modelConfigsSeed: NewModelConfig[] = [
  // ─── IMAGE Models ───────────────────────────────────────────────────────────

  {
    id: "recraft-v3",
    category: "image",
    name: "Recraft V3",
    provider: "recraft",
    promptFormat: "structured",
    supportedSizes: [
      { name: "square_hd", width: 1024, height: 1024, label: "Square HD" },
      { name: "portrait_4_3", width: 768, height: 1024, label: "Portrait 4:3" },
      {
        name: "portrait_16_9",
        width: 576,
        height: 1024,
        label: "Portrait 16:9",
      },
      {
        name: "landscape_4_3",
        width: 1024,
        height: 768,
        label: "Landscape 4:3",
      },
      {
        name: "landscape_16_9",
        width: 1024,
        height: 576,
        label: "Landscape 16:9",
      },
    ],
    qualityOptions: [
      { id: "clean", label: "Clean" },
      { id: "artistic", label: "Artistic" },
    ],
    stylePresets: [
      "Realistic Image",
      "Digital Illustration",
      "Vector Illustration",
      "Icon",
      "Hand Drawn",
      "Pixel Art",
      "Sticker",
      "Doodle",
    ],
    supportsNegativePrompt: false,
    maxPromptLength: 1000,
    documentationUrl: "https://www.recraft.ai/docs",
    specificRules:
      "Recraft V3 uses a structured prompt format. Prompts should describe the subject, style, and composition clearly. Use style tokens from the style_presets list. Avoid generic phrasing; be specific about visual elements, colors, and textures.",
    isActive: true,
  },
  {
    id: "lovart",
    category: "image",
    name: "Lovart",
    provider: "lovart",
    promptFormat: "natural",
    supportedSizes: [
      { name: "1:1", width: 1024, height: 1024, label: "Square 1:1" },
      { name: "16:9", width: 1024, height: 576, label: "Landscape 16:9" },
      { name: "9:16", width: 576, height: 1024, label: "Portrait 9:16" },
      { name: "custom", width: null, height: null, label: "Custom" },
    ],
    qualityOptions: [
      { id: "high", label: "High" },
      { id: "draft", label: "Draft" },
      { id: "300dpi", label: "300 DPI (Print)" },
    ],
    stylePresets: ["Photograph", "Painting", "3D Render", "Sketch"],
    supportsNegativePrompt: false,
    maxPromptLength: null,
    documentationUrl: "https://lovart.ai/docs",
    specificRules:
      "Lovart uses natural language prompts. Supports guidance and style_strength parameters for fine-tuning output. Guidance controls how closely the model follows the prompt (range 1-20). Style_strength adjusts the intensity of the selected style preset (range 0-1).",
    isActive: true,
  },
  {
    id: "leonardo-phoenix",
    category: "image",
    name: "Leonardo Phoenix",
    provider: "leonardo",
    promptFormat: "natural",
    supportedSizes: [
      { name: "1:1", width: 1024, height: 1024, label: "Square 1:1" },
      { name: "16:9", width: 1280, height: 720, label: "Landscape 16:9" },
      { name: "9:16", width: 720, height: 1280, label: "Portrait 9:16" },
      { name: "4:3", width: 1024, height: 768, label: "Landscape 4:3" },
    ],
    qualityOptions: [
      { id: "phoenix_quality", label: "Phoenix Quality" },
      { id: "lightning_xl", label: "Lightning XL" },
    ],
    stylePresets: [
      "Cinematic", "Dynamic", "Vibrant", "Illustration", "Photography",
      "Portrait", "HDR", "Bokeh", "Minimalist", "Moody",
      "3D Render", "Ray Traced", "Sketch (B&W)", "Sketch (Color)",
      "Fashion", "Stock Photo", "Macro", "Creative",
    ],
    supportsNegativePrompt: true,
    maxPromptLength: 1500,
    documentationUrl: "https://docs.leonardo.ai",
    specificRules:
      "Leonardo Phoenix (ID: de7d3faf-762f-48e0-b3b7-9d0ac3a3fcf3) is the flagship foundational model: 5MP+ ultra resolution with 'ultra: true' param, text rendering capability. Use styleUUID for precise style control. Alchemy pipeline enhances image quality (lighting, contrast, detail). Prompt Magic v3 rewrites prompts for better results. Phoenix cannot use Alchemy in ultra mode. Supports contrast param (1.0-4.5). enhancePrompt param for AI prompt improvement.",
    isActive: true,
  },
  {
    id: "leonardo-kino-xl",
    category: "image",
    name: "Leonardo Kino XL",
    provider: "leonardo",
    promptFormat: "natural",
    supportedSizes: [
      { name: "1:1", width: 1024, height: 1024, label: "Square 1:1" },
      { name: "16:9", width: 1344, height: 768, label: "Landscape 16:9" },
      { name: "9:16", width: 768, height: 1344, label: "Portrait 9:16" },
      { name: "4:3", width: 1152, height: 896, label: "Landscape 4:3" },
    ],
    qualityOptions: [
      { id: "kino_quality", label: "Kino Quality" },
      { id: "fast", label: "Fast" },
    ],
    stylePresets: ["Cinematic", "Film Noir", "Vintage", "Documentary", "Photorealistic"],
    supportsNegativePrompt: true,
    maxPromptLength: 1500,
    documentationUrl: "https://docs.leonardo.ai",
    specificRules:
      "Leonardo Kino XL specializes in cinematic and photographic style outputs. Excels at realistic lighting, dramatic compositions, and film-quality aesthetics. Use descriptive cinematic terms (depth of field, golden hour, lens flare). Supports negative prompts.",
    isActive: true,
  },
  {
    id: "leonardo-lightning-xl",
    category: "image",
    name: "Leonardo Lightning XL",
    provider: "leonardo",
    promptFormat: "natural",
    supportedSizes: [
      { name: "1:1", width: 1024, height: 1024, label: "Square 1:1" },
      { name: "16:9", width: 1344, height: 768, label: "Landscape 16:9" },
      { name: "9:16", width: 768, height: 1344, label: "Portrait 9:16" },
    ],
    qualityOptions: [
      { id: "speed", label: "Speed Priority" },
      { id: "balanced", label: "Balanced" },
    ],
    stylePresets: ["Dynamic", "Illustration", "Concept Art", "Product"],
    supportsNegativePrompt: true,
    maxPromptLength: 1500,
    documentationUrl: "https://docs.leonardo.ai",
    specificRules:
      "Leonardo Lightning XL is optimized for fast generation with good quality. Best for rapid iteration and concept exploration. Supports negative prompts. Use clear, direct descriptions for best results.",
    isActive: true,
  },

  // ─── VIDEO Models ───────────────────────────────────────────────────────────

  {
    id: "kling-3.0",
    category: "video",
    name: "Kling 3.0",
    provider: "kling",
    promptFormat: "natural",
    supportedSizes: [
      { name: "16:9", width: 3840, height: 2160, label: "4K Landscape 16:9" },
      { name: "9:16", width: 2160, height: 3840, label: "4K Portrait 9:16" },
      { name: "1:1", width: 2160, height: 2160, label: "4K Square 1:1" },
    ],
    qualityOptions: [
      { id: "standard", label: "Standard" },
      { id: "professional", label: "Professional" },
    ],
    stylePresets: null,
    supportsNegativePrompt: true,
    maxPromptLength: null,
    documentationUrl: "https://app.klingai.com/global/dev/document-api",
    specificRules:
      "Kling 3.0 is the flagship model: native 4K (3840x2160) @ 60fps, 3-15s duration, 6-shot storyboard support, integrated audio generation. Supports 20+ camera presets (pan, tilt, zoom, dolly, orbit, tracking, roll, jib, push-in/pull-out). Use cfg_scale 0.3-0.5 for creative freedom, higher for strict prompt adherence. Negative prompts strongly recommended. Describe camera movement and subject action separately for best results.",
    isActive: true,
  },
  {
    id: "kling-2.6",
    category: "video",
    name: "Kling 2.6",
    provider: "kling",
    promptFormat: "natural",
    supportedSizes: [
      { name: "16:9", width: 1920, height: 1080, label: "Landscape 16:9" },
      { name: "9:16", width: 1080, height: 1920, label: "Portrait 9:16" },
      { name: "1:1", width: 1080, height: 1080, label: "Square 1:1" },
    ],
    qualityOptions: [
      { id: "standard", label: "Standard", costPer5s: 0.2 },
      { id: "professional", label: "Professional", costPer5s: 0.33 },
    ],
    stylePresets: null,
    supportsNegativePrompt: true,
    maxPromptLength: null,
    documentationUrl: "https://app.klingai.com/global/dev/document-api",
    specificRules:
      "Kling 2.6 features simultaneous audio-visual generation (dialogue, sound effects, music). Supports 5s and 10s durations at 1080p. Camera controls: pan, tilt, zoom, orbit, dolly, tracking. Negative prompts reduce unwanted artifacts. Professional mode = higher quality at ~1.65x cost. Describe camera and subject motion explicitly.",
    isActive: true,
  },
  {
    id: "kling-o1",
    category: "video",
    name: "Kling O1",
    provider: "kling",
    promptFormat: "natural",
    supportedSizes: [
      { name: "16:9", width: 1920, height: 1080, label: "Landscape 16:9" },
      { name: "9:16", width: 1080, height: 1920, label: "Portrait 9:16" },
      { name: "1:1", width: 1080, height: 1080, label: "Square 1:1" },
    ],
    qualityOptions: [
      { id: "standard", label: "Standard" },
      { id: "professional", label: "Professional" },
    ],
    stylePresets: null,
    supportsNegativePrompt: true,
    maxPromptLength: null,
    documentationUrl: "https://app.klingai.com/global/dev/document-api",
    specificRules:
      "Kling O1 is the first unified multimodal model: video generation + editing + transformation in one system. Can edit existing videos with text commands. Supports 10 reference images for character/scene consistency. Best for iterative video refinement workflows.",
    isActive: true,
  },
  {
    id: "higgsfield-veo",
    category: "video",
    name: "Veo 3.1 (Higgsfield)",
    provider: "higgsfield",
    promptFormat: "natural",
    supportedSizes: [
      { name: "16:9", width: 1920, height: 1080, label: "Landscape 16:9" },
      { name: "9:16", width: 1080, height: 1920, label: "Portrait 9:16" },
    ],
    qualityOptions: [
      { id: "standard", label: "Standard" },
      { id: "premium", label: "Premium" },
    ],
    stylePresets: ["Cinematic", "Realistic", "Animation"],
    supportsNegativePrompt: false,
    maxPromptLength: null,
    documentationUrl: "https://higgsfield.ai",
    specificRules:
      "Veo 3.1 via Higgsfield platform. Google's video model at 1080p. Supports 4/6/8s durations. Text-to-video and image-to-video. Focus on cinematic quality descriptions, lighting, and atmosphere. Higgsfield adds face swap, character swap, motion transfer, and lip sync post-processing.",
    isActive: true,
  },
  {
    id: "higgsfield-wan",
    category: "video",
    name: "WAN 2.5 (Higgsfield)",
    provider: "higgsfield",
    promptFormat: "natural",
    supportedSizes: [
      { name: "16:9", width: 1920, height: 1080, label: "1080p Landscape" },
      { name: "9:16", width: 1080, height: 1920, label: "1080p Portrait" },
    ],
    qualityOptions: [
      { id: "480p", label: "480p" },
      { id: "720p", label: "720p" },
      { id: "1080p", label: "1080p" },
    ],
    stylePresets: ["Cinematography", "Character Animation", "Dance"],
    supportsNegativePrompt: false,
    maxPromptLength: null,
    documentationUrl: "https://higgsfield.ai",
    specificRules:
      "WAN 2.5 via Higgsfield. Cinematography-focused with virtual camera system. Up to 10s duration. Strong at character animation, dance generation, and motion transfer. Describe camera angles and character movements in detail.",
    isActive: true,
  },
  {
    id: "higgsfield-sora",
    category: "video",
    name: "Sora 2 (Higgsfield)",
    provider: "higgsfield",
    promptFormat: "natural",
    supportedSizes: [
      { name: "16:9", width: 1920, height: 1080, label: "Landscape 16:9" },
      { name: "9:16", width: 1080, height: 1920, label: "Portrait 9:16" },
      { name: "1:1", width: 1080, height: 1080, label: "Square 1:1" },
    ],
    qualityOptions: [
      { id: "standard", label: "Standard" },
      { id: "max", label: "Sora 2 MAX" },
    ],
    stylePresets: ["Realistic", "Cinematic", "Artistic"],
    supportsNegativePrompt: false,
    maxPromptLength: null,
    documentationUrl: "https://higgsfield.ai",
    specificRules:
      "Sora 2 via Higgsfield platform. OpenAI's video model known for realistic, cinematic output with excellent lighting control. Focus on detailed scene descriptions, atmosphere, and natural motion. Sora 2 MAX tier provides highest quality. Available with Higgsfield's face swap and character animation tools.",
    isActive: true,
  },

  // ─── TEXT Models ────────────────────────────────────────────────────────────

  {
    id: "claude-sonnet",
    category: "text",
    name: "Claude Sonnet",
    provider: "anthropic",
    promptFormat: "tags",
    supportedSizes: null,
    qualityOptions: null,
    stylePresets: null,
    supportsNegativePrompt: false,
    maxPromptLength: 200000,
    documentationUrl: "https://docs.anthropic.com",
    specificRules:
      "Claude Sonnet works best with XML-tagged prompts. Use tags like <context>, <instructions>, <examples>, <output_format> to structure prompts. Supports system prompts. Excels at analysis, coding, and creative writing. Balanced speed and quality.",
    isActive: true,
  },
  {
    id: "claude-opus",
    category: "text",
    name: "Claude Opus",
    provider: "anthropic",
    promptFormat: "tags",
    supportedSizes: null,
    qualityOptions: null,
    stylePresets: null,
    supportsNegativePrompt: false,
    maxPromptLength: 200000,
    documentationUrl: "https://docs.anthropic.com",
    specificRules:
      "Claude Opus is the most capable Claude model. Uses XML-tagged prompt format. Best for complex reasoning, nuanced analysis, and expert-level tasks. Use tags like <context>, <instructions>, <constraints> for structure. Higher cost but superior quality for demanding tasks.",
    isActive: true,
  },
  {
    id: "gpt-5.4",
    category: "text",
    name: "GPT-5.4",
    provider: "openai",
    promptFormat: "natural",
    supportedSizes: null,
    qualityOptions: null,
    stylePresets: null,
    supportsNegativePrompt: false,
    maxPromptLength: 1050000,
    documentationUrl: "https://developers.openai.com/api/docs/models/gpt-5.4",
    specificRules:
      "GPT-5.4 is OpenAI's most capable frontier model (March 2026). 1M token context window. Supports reasoning.effort parameter (none/low/medium/high/xhigh) for thinking depth control. Native computer use and Tool Search capabilities. Use Markdown structure with headers, bullet points, and clear sections. Supports structured outputs (JSON mode). 33% fewer factual errors vs GPT-5.2. Best for complex reasoning, agentic workflows, and professional tasks.",
    isActive: true,
  },
  {
    id: "gpt-5.4-thinking",
    category: "text",
    name: "GPT-5.4 Thinking",
    provider: "openai-thinking",
    promptFormat: "natural",
    supportedSizes: null,
    qualityOptions: null,
    stylePresets: null,
    supportsNegativePrompt: false,
    maxPromptLength: 1050000,
    documentationUrl: "https://developers.openai.com/api/docs/models/gpt-5.4",
    specificRules:
      "GPT-5.4 Thinking uses the same model with reasoning.effort set to 'high'. Best for complex multi-step analysis, mathematical reasoning, and tasks requiring deep thought. Uses more tokens for internal reasoning. Reserve at least 25,000 output tokens for reasoning + response.",
    isActive: true,
  },
  {
    id: "gpt-5.4-pro",
    category: "text",
    name: "GPT-5.4 Pro",
    provider: "openai-pro",
    promptFormat: "natural",
    supportedSizes: null,
    qualityOptions: null,
    stylePresets: null,
    supportsNegativePrompt: false,
    maxPromptLength: 1050000,
    documentationUrl: "https://developers.openai.com/api/docs/models/gpt-5.4",
    specificRules:
      "GPT-5.4 Pro is the compute-heavy variant for maximum performance on the hardest tasks. 83.3% on ARC-AGI-2. Use for expert-level analysis, complex code generation, and research tasks. Higher cost ($30/1M input, $180/1M output) but superior quality.",
    isActive: true,
  },
  {
    id: "gpt-4o",
    category: "text",
    name: "GPT-4o",
    provider: "openai",
    promptFormat: "natural",
    supportedSizes: null,
    qualityOptions: null,
    stylePresets: null,
    supportsNegativePrompt: false,
    maxPromptLength: 128000,
    documentationUrl: "https://platform.openai.com/docs",
    specificRules:
      "GPT-4o is a legacy model. Use GPT-5.4 for better results. Works with Markdown-formatted prompts. Supports system, user, and assistant message roles.",
    isActive: true,
  },
  {
    id: "gemini-pro",
    category: "text",
    name: "Gemini Pro",
    provider: "google",
    promptFormat: "natural",
    supportedSizes: null,
    qualityOptions: null,
    stylePresets: null,
    supportsNegativePrompt: false,
    maxPromptLength: 1000000,
    documentationUrl: "https://ai.google.dev/docs",
    specificRules:
      "Gemini Pro supports natural language prompts with Markdown formatting. Excels at multimodal understanding and long-context tasks. Supports very long input contexts. Good for research, analysis, and document understanding.",
    isActive: true,
  },
  {
    id: "kimi-k2.5",
    category: "text",
    name: "Kimi K2.5",
    provider: "moonshot",
    promptFormat: "natural",
    supportedSizes: null,
    qualityOptions: null,
    stylePresets: null,
    supportsNegativePrompt: false,
    maxPromptLength: 128000,
    documentationUrl: "https://platform.moonshot.cn/docs",
    specificRules:
      "Kimi K2.5 uses natural language prompts. Strong at Chinese and English bilingual tasks. Supports long-context inputs. Good at coding, mathematical reasoning, and document analysis.",
    isActive: true,
  },
  {
    id: "qwen",
    category: "text",
    name: "Qwen",
    provider: "alibaba",
    promptFormat: "natural",
    supportedSizes: null,
    qualityOptions: null,
    stylePresets: null,
    supportsNegativePrompt: false,
    maxPromptLength: 128000,
    documentationUrl: "https://help.aliyun.com/zh/model-studio",
    specificRules:
      "Qwen uses natural language prompts. Strong multilingual capabilities with emphasis on Chinese and English. Good at coding, math, and general reasoning. Supports function calling and tool use.",
    isActive: true,
  },
];
