export const researchKling30Prompts = [
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "A dim kitchen late at night. Only the refrigerator hum fills the silence. A plate is set down too hard. Ceramic clinks sharply. [Character A: Exhausted Partner, trembling frustrated voice]: “You never listen to me.” Immediately, the other partner turns around, eyes wide. [Character B: Defensive Partner, shouting loudly]: “Because you never stop blaming!” The exhausted partner exhales shakily. [Exhausted Partner, voice cracking]: “I’m not blaming… I’m begging.” Silence. The defensive partner sighs heavily. [Defensive Partner, softly, regretful]: “I don’t know how to fix this.” A sad piano chord enters quietly.",
    tags: ["Cinematic/Dialogue"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Establishes characters early, uses bold tone descriptions for realistic dialogues, clear sequence of events.",
    modelNotes: "Demonstrates multi-character dialogue and emotional nuance.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "A sleek modern interrogation room with cold LED lighting. Muted gray walls, a glass window, security cameras blinking red. Low atmospheric suspense music hums with deep bass drones. A detective in a navy suit leans forward slowly. His hands rest calmly on the table. [Character A: Lead Detective, controlled serious voice]: “Let’s stop pretending.” Immediately, the suspect shifts in their chair, tense. [Character B: Prime Suspect, sharp defensive voice]: “I already told you everything.” The detective slides a folder across the table. Paper scraping sound. [Lead Detective, calm but threatening tone]: “Then explain why your fingerprints are here.” The suspect’s breathing quickens. [Prime Suspect, voice trembling]: “That’s impossible…” The detective stands suddenly, chair scraping back. Music tightens with a rising pulse.",
    tags: ["Cinematic/Dialogue"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Establishes characters and dialogue sequence clearly, uses keywords for pace and tonality, understands cinematic language, builds suspense.",
    modelNotes: "Effective use of environmental details and sound cues.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "Joker begins his iconic dance descent down the stairs, arms outstretched, pure chaotic joy.",
    tags: ["Cinematic/Narrative"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Describes progression over time, actions, camera reactions, and scene transitions for longer durations, demonstrating multi-shot capability.",
    modelNotes: "Shows how to break down a complex scene into multiple shots for better control.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "A busy kitchen in the morning. Cereal pouring. Coffee machine buzzing. Kids running footsteps. Backpack zippers. A mother flips toast quickly, stressed. [Character A: Mom, fast urgent voice]: “Shoes on! We’re leaving in five minutes!” Immediately, a little girl whines from the hallway. [Character B: Little Daughter, crying voice]: “I can’t find my sweater!” The older brother groans dramatically. [Character C: Older Brother, annoyed sarcastic tone]: “Because you never put it away.” Mom sighs heavily. [Mom, shouting louder]: “Nobody is fighting before 8 AM!” The dad walks in calmly sipping coffee. [Character D: Dad, sleepy amused voice]: “Good morning, team.” Mom turns sharply. [Mom, exhausted voice]: “Help.”",
    tags: ["Cinematic/Dialogue"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed character interactions, distinct voices and emotions, realistic scenario.",
    modelNotes: "Good example of managing multiple characters and their dialogue in a dynamic scene.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "Inside a parked car at night. Rain tapping softly on the roof. Low lo-fi music playing from the speakers. A driver grips the steering wheel, nervous. [Character A: Driver Friend, hesitant voice]: “So… are you mad at me?” Immediately, the passenger stares out the window. [Character B: Passenger Friend, quiet cold tone]: “I don’t know.” The driver swallows. [Driver Friend, softly speaking]: “That’s worse than yes.” The passenger sighs deeply. [Passenger Friend, tired voice]: “I just didn’t expect it from you.”",
    tags: ["Cinematic/Dialogue"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Captures a specific mood and emotional tension, uses environmental sounds, and distinct character voices.",
    modelNotes: "Highlights the model's ability to handle subtle emotional cues and atmospheric details.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "A quiet park bench in the late afternoon. Birds chirping. Wind through trees. Soft acoustic guitar music. Two old friends sit side by side. One smiles softly. [Character A: Old Friend 1, warm nostalgic voice]: “It’s been… what, ten years?” Immediately, the other laughs quietly. [Character B: Old Friend 2, emotional voice]: “Too long.” Pause. [Old Friend 1, softly speaking]: “I missed you.” The other nods slowly. [Old Friend 2, whispering]: “Me too.”",
    tags: ["Cinematic/Dialogue"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Evokes nostalgia and warmth, uses ambient sounds, and conveys emotional depth through dialogue.",
    modelNotes: "Good for generating emotionally resonant, character-driven scenes.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "A scene with a family of four watching TV. Woman: \"Wow, I didn't expect this plot at all.\" Man: \"Yeah, it's totally unexpected. Never thought that would happen.\" Boy: \"It's the best twist ever!\" Girl: \"I can't believe they did that.\"",
    tags: ["Cinematic/Dialogue"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Demonstrates multi-character dialogue with corresponding camera cuts.",
    modelNotes: "Good for testing multi-character dialogue and camera switching.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "Warm sunlight washes over the old streets of Madrid. Outside a small street-side bakery, a female tourist and a male tourist in a blue shirt step up to the counter, both smiling politely. Female tourist (carefully, with a noticeable accent, in Spanish): 'Hola... perdón. ¿Como llegamos al centro?' The white-haired Spanish shop clerk turns slightly and gestures down the street, friendly and relaxed. Shop clerk (in Spanish): 'Todo recto, y luego a la derecha. No tiene pérdida.' The female tourist nods, slightly relieved. Female tourist (in Spanish): 'Ah, vale... gracias.' The male tourist smiles and adds, Male tourist (in Spanish): 'Perfecto, muchas gracias.' The shop clerk smiles back and gives a small nod. The two tourists turn and walk off together, following the direction he pointed, blending into the sunlit street.",
    tags: ["Cinematic/Dialogue"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed setting, character actions, and exact multi-language dialogue for a natural animated short.",
    modelNotes: "Highlights the model's ability to handle specific languages and accents.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "@predator slowly walking behind him, a man is on stage doing stand-up comedy, he says 'He's behind me isn't he...', then slowly walks behind him and pushes him",
    tags: ["Cinematic/Character Consistency"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Demonstrates character consistency using the \"Elements\" feature and specific actions.",
    modelNotes: "Effective use of the `@` symbol for referencing custom characters.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "a wizard laughing uncontrollably",
    tags: ["Cinematic/Emotional"],
    quality: 0.6,
    source: "research_2",
    domain: "general",
    whyItWorks: "Simple prompt to generate strong emotional performance.",
    modelNotes: "Good for testing basic emotional expressions.",
    rating: 3,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "a man crying uncontrollably",
    tags: ["Cinematic/Emotional"],
    quality: 0.6,
    source: "research_2",
    domain: "general",
    whyItWorks: "Simple prompt to generate strong emotional performance.",
    modelNotes: "Good for testing basic emotional expressions.",
    rating: 3,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "A man and his dog getting ready for a walk, Pixar style animation.",
    tags: ["Animation Style"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Specifies a distinct animation style for the output.",
    modelNotes: "Shows the model's capability to adapt to different artistic styles.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "A lonely old man making tea and remembering his late wife, claymation style.",
    tags: ["Animation Style"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Specifies a distinct animation style and conveys a narrative.",
    modelNotes: "Demonstrates the model's ability to render in specific artistic styles.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "Cinematic sunset scene on a coastal balcony overlooking the sea. A young woman wearing a light linen dress leans on the railing as waves crash below. The camera slowly dolly-moves forward. She sighs softly and says, “I always forget how loud the ocean can be.” Shot 2: Cut to a medium close-up of a young man placing two cups of tea on the table, replying calmly, “That’s because you only notice it when you stop running.” Shot 3: Over-the-shoulder shot from behind the woman as she turns, smiles faintly, and asks, “And you? Do you ever stop?” Natural lighting, warm color grading, realistic facial expressions, gentle ambient wind and distant seagulls, cinematic realism.",
    tags: ["Cinematic/Dialogue"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Uses multi-shot for different perspectives, detailed scene and character descriptions, includes audio and visual cues, and cinematic realism.",
    modelNotes: "Demonstrates multi-shot and cinematic intent with emotional depth.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "Shot 1: \"A wide shot of the woman walking through the park.\" Shot 2: \"A close-up as she smiles and waves at a friend.\" Shot 3: \"A tracking shot as she turns to look behind her, following the camera movement as she keeps walking.\"",
    tags: ["Cinematic/Multi-shot"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Clear shot descriptions and camera movements for a simple narrative.",
    modelNotes: "Basic multi-shot example focusing on camera work.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "Shot 1: \"A cinematic shot on a European villa’s terrace. A young Caucasian woman in a blue-and-white striped shirt and khaki shorts sits at a table. The camera slowly pushes in.\" Shot 2: \"The woman swirls juice in her glass, gazing at the distant woods, and says, 'These trees will turn yellow in a month.'\" Shot 3: \"Close-up of a young Caucasian man in a white T-shirt, who whispers, 'But they'll be green again next summer.'\" Shot 4: \"The woman turns and smiles, 'Are you always this optimistic?' The man replies, 'Only about summers with you.'\" Atmosphere: \"High-quality, 4K, realistic textures, natural sunlight, with an emotional atmosphere.\"",
    tags: ["Cinematic/Dialogue"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Multi-shot structure, detailed atmosphere, and character dialogue with emotional context.",
    modelNotes: "Good for complex scenes with multiple characters and emotional undertones.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "The woman smiles as the man, standing beside her, whispers something in her ear. The camera alternates between their faces.",
    tags: ["Cinematic/Multi-character"],
    quality: 0.6,
    source: "research_2",
    domain: "general",
    whyItWorks: "Focuses on character interaction and camera alternation.",
    modelNotes: "Simple example for multi-character coreference.",
    rating: 3,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "Interior café scene during a rainy afternoon. The barista, speaking cheerfully: “Your drinks will be ready in just a moment.” The woman in the red coat, turning toward her friend, whispers: “I told you this place was worth the wait.” The man with glasses, smiling quietly, replies: “You were right this time.” Camera alternates between medium shots and close-ups, rain tapping softly against the windows, ambient café chatter in the background.",
    tags: ["Cinematic/Dialogue"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed setting, distinct character voices, and ambient sounds create a realistic scene.",
    modelNotes: "Effective use of audio and visual details for atmosphere.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "The woman speaks in fluent French: 'Je t'aime,' as the man responds in English: 'I love you too.' The accent and lip-sync match perfectly.",
    tags: ["Cinematic/Multilingual"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Explicitly defines languages and emphasizes perfect accent and lip-sync.",
    modelNotes: "Highlights Kling 3.0's multilingual capabilities.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "A small night market street in Tokyo illuminated by hanging lanterns. The vendor speaks in Japanese with a friendly tone: “今日は寒いですね。” A tourist responds in slightly accented Japanese: “はい、でも雰囲気が素敵です。” Her companion adds softly in English: “This feels like a movie scene.” Natural mouth movement, accurate lip sync, gentle crowd noise, light wind brushing fabric and paper lanterns.",
    tags: ["Cinematic/Multilingual"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Rich environmental description, multi-language dialogue with accents, and detailed audio/visual cues.",
    modelNotes: "Excellent example of combining multilingual dialogue with atmospheric details.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "Scene: \"A cozy indoor home environment with a soft hum of an air conditioner in the background.\" Dialogue: Mother (in surprise): \"Wow, I didn’t expect this plot at all!\" Father (calmly): \"Yeah, it’s totally unexpected, never thought that would happen.\" Boy (excited): \"It’s the best twist ever!\" Girl (nodding): \"I can't believe they did that!\" Additional Detail: \"The dialogue is in clear English with realistic lip movements and expressions.\"",
    tags: ["Cinematic/Dialogue"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Multi-character dialogue with emotional expressions and clear language specification.",
    modelNotes: "Demonstrates multi-character coreference and realistic lip movements.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "The woman’s red dress remains the same throughout the video, even as the camera zooms and shifts around her.",
    tags: ["Subject Consistency"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Explicitly states the need for subject consistency despite camera movements.",
    modelNotes: "Simple yet effective for testing subject consistency.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "Scene: \"A close-up of a woman in a red dress standing by a scenic mountain lake. The camera orbits around her, capturing her face as she smiles warmly.\" Subject Consistency: \"Throughout the video, the woman’s red dress and long brown hair remain consistent as the camera moves.\" Action: \"The woman lifts her head and looks directly at the camera, smiling as if seeing an old friend after years.\"",
    tags: ["Image-to-Video/Subject Consistency"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Combines image-to-video with strong subject consistency and emotional action.",
    modelNotes: "Ideal for advertising or branded content where visual details must be maintained.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "Scene: \"A low-angle shot of a young woman running at full speed through a moonlit garden.\" Action: \"As she runs, her skirt billows in the wind, and she holds a small white flower in her hand. Several people in vintage formal attire run parallel to her, creating a sense of chase.\" Camera Movement: \"At the 8-second mark, the camera zooms into a close-up, then tracks her as she glances back at a young man, locking eyes for a brief moment.\" Ending: \"In the final 3 seconds, the couple breaks through the crowd and runs toward the starry sky, the camera following their movement.\"",
    tags: ["Cinematic/Narrative"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed narrative progression, specific camera movements, and clear time markers for a longer video.",
    modelNotes: "Leverages Kling 3.0's longer duration capabilities for complex storytelling.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "Wide tracking shot through a quiet train station at dawn. 0–4s: A young man walks briskly along the platform, breath visible in cold air. 5–9s: The camera accelerates slightly as he spots a woman ahead and slows down. 10–13s: Close-up as their eyes meet; background sound fades. 14–15s: The train doors close behind them as they smile softly. Muted color palette, cinematic pacing, natural movement, emotional restraint.",
    tags: ["Cinematic/Narrative"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Uses time markers for precise control over a longer narrative, detailed visual and audio cues, and emotional context.",
    modelNotes: "Excellent for continuous storytelling and dynamic scene progression.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "Modern office hallway with low ambient noise. The woman in a navy blazer says confidently: “Send the proposal before noon.” The assistant responds quickly, slightly nervous: “Already queued for delivery.” Footsteps echo softly, voices clearly tied to the correct speakers, natural reverb and spatial audio.",
    tags: ["Cinematic/Dialogue"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Realistic office setting, clear dialogue attribution, and detailed audio environment.",
    modelNotes: "Good for professional or corporate video generation.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "Morning sunlight fills a minimalist studio kitchen. The camera glides across a marble countertop toward a matte black coffee machine. Clean engraved lettering on the machine reads: “Brew Calm.” A soft voiceover begins: “Every morning deserves intention.” Steam rises naturally, reflections remain sharp, typography is crisp and readable.",
    tags: ["E-commerce/Branding"],
    quality: 1.0,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Focuses on product presentation, clear text rendering, and atmospheric details for advertising.",
    modelNotes: "Highlights native-level text rendering and product-focused video generation.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "Warm family living room at night. The grandmother speaks in a slow regional dialect with a soft laugh: “Back in my day, we didn’t rush so much.” The teenager replies in casual modern slang: “Yeah, but things move faster now.” The mother chuckles quietly between them. Subtle background TV hum, realistic pauses, expressive facial movements, cozy lighting.",
    tags: ["Cinematic/Dialogue"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Uses distinct dialects and slang, realistic family interaction, and detailed environmental cues.",
    modelNotes: "Demonstrates Kling 3.0's ability to handle diverse linguistic nuances.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "Shot 1 (6s): Handheld medium shot on a snowy hillside. @Male lead laughs nervously and says, “Maybe we chose the coldest place possible.” Shot 2 (9s): Camera pans to @Female lead smiling warmly: “At least we’ll remember it forever.” Natural camera shake, wind audio, cinematic realism, smooth transition between shots.",
    tags: ["Cinematic/Dialogue"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Uses shot-level precision with time markers, character referencing, and detailed audio/visuals.",
    modelNotes: "Excellent for Omni Storyboard control and multi-shot cinematic realism.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "A motorcycle rider in a black leather jacket speeds through neon-lit city streets at night, rain-slicked roads reflecting colorful lights. Camera follows from behind then sweeps to a low side angle. Motion blur on background, rider in sharp focus. Cinematic color grade with teal and orange.",
    tags: ["Cinematic", "Action"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Dynamic camera movement + motion blur technique + specific color grade creates high-energy cinematic action.",
    modelNotes: "Kling 3.0 excels at motion blur and dynamic camera transitions. Teal-orange grade is a reliable cinematic preset.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "Anime style, a young female warrior with silver hair and glowing violet eyes stands on a cliff overlooking a burning city at sunset. Her tattered cape flows in the wind. She grips a glowing sword. Dramatic lighting, detailed background, Studio Ghibli-inspired color palette.",
    tags: ["Anime", "Character"],
    quality: 0.8,
    source: "research_2",
    domain: "illustration",
    whyItWorks: "Anime style specification + detailed character description + Studio Ghibli reference creates consistent anime aesthetic.",
    modelNotes: "Kling 3.0 has strong anime generation. Studio Ghibli reference triggers warm, painterly color palettes.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "Vertical format (9:16), a barista in a cozy café carefully pours latte art into a ceramic cup. Close-up of the pour, steam rising, warm amber lighting. Slow motion at the pour moment. Aesthetic and satisfying. Instagram Reels style.",
    tags: ["Lifestyle", "Social Media"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Vertical format specification + satisfying close-up action + slow motion moment creates viral-worthy social content.",
    modelNotes: "Kling 3.0 vertical format (9:16) optimized for TikTok/Instagram. 'Satisfying' keyword triggers smooth, pleasing motion.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "Aerial drone shot slowly descending into a mystical forest where ancient trees have glowing blue bioluminescent roots. Fireflies drift through shafts of moonlight. Mist clings to the forest floor. Ethereal, magical atmosphere. Fantasy film aesthetic.",
    tags: ["Fantasy", "Landscape"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Aerial descent + bioluminescence + layered atmospheric elements (mist, fireflies, moonlight) creates immersive fantasy world.",
    modelNotes: "Kling 3.0 handles complex atmospheric layering well. Bioluminescence is a reliable visual trigger for magical aesthetics.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "Medium shot of an elderly craftsman in his workshop, hands weathered and skilled, carefully carving wood with a chisel. Warm workshop lighting, sawdust in the air, tools hanging on the wall behind him. He looks up and smiles at the camera. Documentary style, natural lighting.",
    tags: ["Documentary", "Interview"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Authentic character detail + natural setting + documentary style creates emotional, human-centered storytelling.",
    modelNotes: "Kling 3.0 captures authentic human moments well. 'Documentary style' triggers natural, unposed aesthetics.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "kling-3.0",
    prompt: "A dark corridor in an abandoned hospital. A figure in a white dress stands at the far end, completely still. The camera slowly dolly-zooms toward her (Hitchcock zoom effect). Flickering fluorescent lights. She turns her head 180 degrees. Audio: Silence broken by a single, distant heartbeat.",
    tags: ["Horror", "Supernatural"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Hitchcock zoom reference + specific impossible action (180-degree head turn) + audio contrast creates maximum horror impact.",
    modelNotes: "Kling 3.0 can execute Hitchcock zoom (dolly zoom) effectively. Naming the technique gives precise results.",
    rating: 5,
  },
];
