export const researchSeedreamPrompts = [
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Female marine biologist on research vessel deck, weathered face with genuine smile, holding water sampling equipment, ocean horizon in background, golden hour side lighting, documentary photography style, sense of dedication and expertise",
    tags: ["photorealistic"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Turn (provide a reference image) this picture into a professional headshot. The person should be wearing a neat dark grey suit with a tie and a clean hairstyle. Keep the background minimal. Sharp focus on eyes, natural skin texture, subtle smile, high resolution, and clean composition.",
    tags: ["photorealistic"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Extreme macro photography of honey being poured from a wooden dipper onto a slice of bread. The honey strand catches warm backlight, showing its amber transparency. Tiny air bubbles are visible inside the pour. The background is soft and out of focus with warm kitchen tones. Natural morning window light from the right. Shallow depth of field, no text, no props outside the pour and bread.",
    tags: ["photorealistic"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Leather watch on textured concrete block, brass accents catching warm directional light, shallow depth with blurred industrial elements in background, masculine luxury positioning.",
    tags: ["photorealistic"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "A male model sliding down a stairway with a skateboard. The time is around dusk with a greyish sky. The pattern on the skateboard matches with the colors of the model’s shirt. Make it look stylish and unique. ",
    tags: ["photorealistic"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Create a dramatic closeup of a woman with terror in her eyes and ready to run. Dark lighting setup with a tense mood.",
    tags: ["cinematic"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Generate an image of a soldier running with a bomb in his hand and a tank behind him. Create an intense environment with dust on the soldier’s face. It should be a wide shot with dramatic lighting showing explosions and smoke around the tank behind the soldier.",
    tags: ["cinematic"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Create a post-apocalyptic cityscape at dusk with a person standing in the middle of the road. Smoke coming from the buildings fills the air. The background includes cars colliding with each other. Cinematic wide-angle composition, realistic textures, dynamic lighting, desaturated colors with warm highlights, and moody atmosphere.",
    tags: ["cinematic"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "An aerial shot of a girl standing alongside a beautiful white horse on a mountain with lots of flowers. The overall mood is happy and exciting. Blue sky and a panoramic view of the whole mountain. Add golden hour sunlight casting dramatic shadows everywhere.",
    tags: ["cinematic"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Soft, high-contrast portrait with the subject is next to a large, sheer-curtained window with a cup of coffee in hand and a subtle warm smile. Natural soft light illuminates one side of the face while the other falls into a deep, velvety shadow. Muted, warm color grade, peaceful, contemplative mood.",
    tags: ["cinematic"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Anime-style portrait of a mysterious sorceress with glowing runes and a dark forest backdrop. Surrounded by floating leaves with ethereal fog in the background. The atmosphere is enigmatic with dramatic lighting.",
    tags: ["anime/illustration"],
    quality: 0.8,
    source: "research_2",
    domain: "illustration",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "A cartoon illustration of a fox rendered in bold pen-and-ink line art with heavy cross-hatching and stippling, overlaid with flat, watercolor-style color washes and subtle halftone texture. Use a slightly muted, desaturated palette. Overall composition should balance impactful line work and washes with a polished digital finish reminiscent of traditional print illustration.",
    tags: ["anime/illustration"],
    quality: 0.8,
    source: "research_2",
    domain: "illustration",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Anime-style image of a superhero team in dynamic action poses. The team has 5 members with 2 girls and three boys ready for action. Exaggerated facial expressions with everyone crossing their hands. The overall mood should be exciting with high contrast shadows.",
    tags: ["anime/illustration"],
    quality: 0.8,
    source: "research_2",
    domain: "illustration",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Create an image of a cartoon character standing in the middle of a road in the future with flying cars. The background should have robots working on food carts. Use a bright neon color palette. Make it anime-style.",
    tags: ["anime/illustration"],
    quality: 0.8,
    source: "research_2",
    domain: "illustration",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Turn (insert a reference image) the image into a ghibli style portrait with the girl riding a bike in the middle of a street with the background of Japanese homes. Natural lighting with warm hues.",
    tags: ["anime/illustration"],
    quality: 0.8,
    source: "research_2",
    domain: "illustration",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Create an oil painting of a serene countryside landscape, with rolling hills and a clear blue sky. It should be a wide-shot painting with warm colors.",
    tags: ["artistic"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Using the provided reference photo, recreate the same person as a highly detailed Black INK hand-drawn sketch, exactly like a ballpoint pen illustration. Preserve the exact facial likeness and maintain the original clothing. Fine pen line work, cross-hatching, layered strokes, and controlled shading to create depth and realism. The background must be plain white or very lightly textured paper. No colors other than blue ink are allowed anywhere in the image.",
    tags: ["artistic"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Landscape painting of an autumn day in the thick woods, falling leaves in a golden and red hue, sunlight penetrating the foliage, twisting forest trail, oil paint style, painterly brushwork, realistic shadows and lights, warm color scheme, ultra-detailed, high-resolution, warm and cozy atmosphere.",
    tags: ["artistic"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Realistic view of a rustic wooden table, fruit on it, a glass of water, a ceramic vase, soft directional light, shadows and textures, oil painting style, high realism, subtle reflections, ultra-definition, calm and timeless mood, 4K resolution, pensive and serene atmosphere.",
    tags: ["artistic"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Abstract expressionism painting of a cityscape, vibrant colors, dynamic brushstrokes, emotional intensity.",
    tags: ["artistic"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Design a 3D character based on Pixar animation; a young happy adventurer with expressive eyes and playful attitude wearing a slightly worn-out backpack. Soft cinematic light, smooth textures, detailed, but soft and subtle, and vivid colors.",
    tags: ["cgi/3d render"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Create a realistic 3D environment of a futuristic city plaza at nightfall, wet sidewalks with neon lights, and interior lights in the shops. Real glass, metal, and concrete should be used, and the lighting should be moving and cinematic.",
    tags: ["cgi/3d render"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "A 3D portrait of a friendly-looking middle-aged man, facial features a soft texture with a few flaws, hands in their natural form, soft shadows with warm light, slightly exaggerated proportions such as a stop-motion figure, and handcrafted, playful appearance.",
    tags: ["cgi/3d render"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Create a 3D isometric image of a comfortable modern living room, wood, sun rays coming in through the large windows, soft fabrics on the couch and cushions, bookshelf with some books scattered, plants inside, warm lighting ambiance, natural shadows, natural sense of space, consideration of scale and viewpoint.",
    tags: ["cgi/3d render"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Make a 3D render of a luxury sports car parked on a mountain road at golden hour, the reflection on polished surfaces, treads on tires and brake calipers, the dust on the car, the soft sunlight playing along curves, real-world environment with rocks and trees, cinematic wide-angle shot.",
    tags: ["cgi/3d render"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "The product image should contain high-resolution product images, a solid package design, product benefits and promotional text with a color scheme of dominating dark and light green.",
    tags: ["e-commerce"],
    quality: 0.8,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "A fashioned flat lay of a high-end skin care company. White marble surface. There are three glass skincare bottles that are loosely placed in a triangle shape. Far left diffused light on the window. Light pink and creamy color scheme in the entire.",
    tags: ["e-commerce"],
    quality: 0.8,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Gold bracelet on textured platform, brass accents catching warm directional light, shallow depth with blurred industrial elements in background, feminine luxury vibes.",
    tags: ["e-commerce"],
    quality: 0.8,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Cold brew coffee being poured into a glass with ice, catching droplets and movement, condensation on the glass visible, summer afternoon light, refreshing and appealing atmosphere.",
    tags: ["e-commerce"],
    quality: 0.8,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Create a magazine cover similar to Vogue magazine with (insert your magazine name) written on it. Use the (insert an image) as the cover image. Maintain her pose and facial expression, style her in a chic outfit with a flowing coat, soft golden hour lighting to highlight her features, cinematic color grading, realistic skin and hair textures, bold typography placeholders for title and headlines, dynamic composition.",
    tags: ["e-commerce"],
    quality: 0.8,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Detailed description, specific style elements.",
    modelNotes: "Seedream 5.0 compatible. Focus on detailed descriptions for better output.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "A rainy Tokyo street at night, neon lights flickering, wet pavement reflecting the glow",
    tags: ["cinematic"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Specific location, time, lighting, and atmosphere details.",
    modelNotes: "Seedance 2.0 (Seedream 2.0) benefits from highly detailed scene descriptions.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "A young agent wearing a black trench coat, looking tense",
    tags: ["cinematic"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed character description including clothing and emotion.",
    modelNotes: "Detailed subject descriptions ensure character consistency.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "He quickly moves through the crowd, whispers into his earpiece, and glances back",
    tags: ["cinematic"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Continuous and descriptive actions for fluid video.",
    modelNotes: "Avoid single actions; use continuous movements for natural video generation.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Start with a wide shot, track the protagonist’s movement, and finish with a push-in close-up",
    tags: ["cinematic"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Explicit camera movements for controlled video output.",
    modelNotes: "Specifying camera language is a key advantage of Seedance 2.0; otherwise, results may be random.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Cool-toned cinematic style, high contrast, shallow depth of field",
    tags: ["cinematic"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Specific visual style elements for desired aesthetic.",
    modelNotes: "Seedance 2.0 allows detailed control over visual texture and mood.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Deep electronic music, gradually intensifying as the camera pushes forward",
    tags: ["cinematic"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Integration of sound with visual progression.",
    modelNotes: "Seedance 2.0 supports synchronization between music and visuals.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Professional product photography of a minimalist white ceramic coffee mug on a light oak wooden surface. Soft natural window light from the left, creating gentle shadows. Clean and modern aesthetic. White background with subtle texture. Shot from a 45-degree angle. High resolution, commercial quality.",
    tags: ["E-commerce", "Product Photography"],
    quality: 1.0,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Specific surface material + light direction + angle + commercial quality modifier creates professional e-commerce imagery.",
    modelNotes: "Seedream 2.0 excels at product photography. Specifying light direction and surface material dramatically improves quality.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Editorial fashion portrait of a woman with natural curly hair wearing a structured blazer in deep burgundy. Shot against a textured concrete wall. Dramatic side lighting creating strong shadows. High fashion magazine aesthetic. Sharp focus on face, slight background blur. Film photography look.",
    tags: ["Portrait", "Fashion"],
    quality: 1.0,
    source: "research_2",
    domain: "photography",
    whyItWorks: "Specific clothing description + dramatic lighting direction + magazine aesthetic reference creates editorial-quality portrait.",
    modelNotes: "Seedream 2.0 handles complex lighting and fashion aesthetics well. Film photography look adds authentic texture.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Interior architectural photography of a modern minimalist living room. Floor-to-ceiling windows overlooking a forest. Neutral palette: white walls, warm wood floors, cream linen sofa. Late afternoon golden light streaming in. Architectural Digest style. Wide angle lens perspective.",
    tags: ["Architecture", "Interior"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Specific architectural elements + color palette + publication reference + lighting time creates professional interior visualization.",
    modelNotes: "Architectural Digest reference is a strong quality trigger for Seedream 2.0 interior shots.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Overhead flat lay of a rustic Italian pasta dish in a ceramic bowl. Fresh basil leaves, cherry tomatoes, parmesan shavings. Worn wooden table surface. Soft diffused natural light. Moody, warm tones. Food styling with scattered ingredients around the bowl. Restaurant quality photography.",
    tags: ["Food Photography"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Flat lay specification + specific ingredients + surface texture + food styling instruction creates appetizing food content.",
    modelNotes: "Seedream 2.0 food photography is exceptional. Overhead/flat lay angle consistently produces the best results.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Whimsical children's book illustration of a small fox wearing a tiny backpack, exploring a magical mushroom forest. Watercolor style with soft pastel colors. Warm, inviting atmosphere. Detailed but gentle linework. Suitable for ages 3-8. Inspired by classic Beatrix Potter illustrations.",
    tags: ["Illustration", "Children's Book"],
    quality: 0.8,
    source: "research_2",
    domain: "illustration",
    whyItWorks: "Age-appropriate specification + watercolor style + specific illustration reference creates consistent children's book aesthetic.",
    modelNotes: "Beatrix Potter reference is a reliable trigger for classic children's illustration style in Seedream 2.0.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-seedream-5.0",
    prompt: "Abstract digital art inspired by the cosmos. Swirling nebulae in deep purple, electric blue, and gold. Microscopic and macroscopic scales merged. Intricate fractal patterns within the cosmic clouds. Dark background with pinpoints of light. High detail, gallery-quality digital artwork.",
    tags: ["Abstract", "Art"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Scale contrast (microscopic/macroscopic) + specific color palette + fractal reference creates complex abstract imagery.",
    modelNotes: "Seedream 2.0 handles abstract cosmic imagery well. Fractal reference adds mathematical precision to organic forms.",
    rating: 4,
  },
];
