export const researchSeedancePrompts = [
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "Sweeping drone shot ascending from a misty valley floor, slowly revealing a vast mountain range at sunrise, golden light breaking through clouds and casting long shadows across pine forests, orchestral grandeur, National Geographic documentary quality, ultra-smooth camera movement",
    tags: ["Cinematic & Film"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Upward camera motion creates tension and release. Referencing 'National Geographic documentary quality' significantly enhances production value. Effective about 9/10 times.",
    modelNotes: "Best settings: 16:9, 12-15 seconds, 1080p",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "Extreme close-up of a young woman's face, eyes slowly opening to reveal reflected city lights, a single tear rolling down her cheek catching the light, shallow depth of field with bokeh background, intimate and emotional, Blade Runner cinematography style, warm amber and cool blue color contrast",
    tags: ["Cinematic & Film"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Seedance 2.0 excels at capturing small facial details and emotional subtleties. The 'Blade Runner' reference establishes a strong, filmic color palette. High shareability factor.",
    modelNotes: "Best settings: 16:9, 8-10 seconds, 1080p",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "A martial artist performing a spinning kick in slow motion, silk ribbons trailing from their wrists creating spiral patterns in the air, ancient temple courtyard setting with cherry blossom petals falling, dramatic side-angle tracking shot, Crouching Tiger Hidden Dragon aesthetic, golden hour backlighting creating silhouette effect",
    tags: ["Cinematic & Film"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Model handles complex body mechanics well. Silk ribbons add visual flow and can mask minor imperfections in motion rendering. Atmospheric details enhance the scene.",
    modelNotes: "Best settings: 16:9, 10-12 seconds, 1080p",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "A detective in a trench coat walking down a rain-soaked alley at night, neon signs reflecting in puddles creating streaks of red and blue light, steam rising from a manhole, slow dolly shot following from behind, film noir style, high contrast with deep shadows, 1940s meets cyberpunk",
    tags: ["Cinematic & Film"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Seedance 2.0 excels with neon reflections on wet surfaces, often rivaling hand-crafted VFX. High contrast and unique stylistic blends ('1940s meets cyberpunk') yield strong, atmospheric results.",
    modelNotes: "Best settings: 21:9, 10-15 seconds, 1080p",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "A premium wristwatch floating in mid-air, slowly rotating with precision, water droplets suspended around it catching the light like diamonds, pure black background with a single dramatic spotlight from above, extreme macro detail showing every texture on the watch face, high-end jewelry commercial aesthetic, ultra-smooth rotation",
    tags: ["Product & Commercial"],
    quality: 1.0,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Reliably produces professional-looking product shots. Floating rotation is a standard for product videos, and Seedance handles it smoothly. Water droplets add a luxurious feel.",
    modelNotes: "Best settings: 1:1 or 16:9, 8-10 seconds, 1080p",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "A tall glass of iced coffee being poured in slow motion, rich dark coffee meeting swirling cream creating mesmerizing patterns, ice cubes clinking and shifting, condensation droplets on the glass surface, close-up shot transitioning to medium shot, warm cafe lighting, Starbucks commercial quality, appetizing and inviting mood",
    tags: ["Product & Commercial"],
    quality: 1.0,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Slow-motion pouring is a highly effective advertising format. The mesmerizing vortex pattern is hypnotic and loopable, boosting algorithmic distribution. Generates content indistinguishable from professional footage.",
    modelNotes: "Best settings: 16:9, 8-10 seconds, 1080p",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "A smartphone rising from its packaging, layers of protective film peeling away in satisfying slow motion, the screen illuminating to reveal a vibrant home screen, clean environment with soft directional lighting, Apple keynote presentation style, futuristic and aspirational",
    tags: ["Product & Commercial"],
    quality: 0.8,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "The 'peeling away' effect is key for satisfying unboxing videos. Seedance 2.0 captures this palpable quality. Works well for consumer electronics with strong visual identities.",
    modelNotes: "Best settings: 9:16, 8-12 seconds, 1080p",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "Model walking on an infinite white cyclorama, wearing an oversized camel wool coat, fabric flowing with each step, camera tracking alongside at hip height, wind machine creating gentle fabric movement, clean editorial fashion photography style, soft diffused studio lighting, Zara campaign aesthetic",
    tags: ["Product & Commercial"],
    quality: 0.8,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Effective for e-commerce, focusing on fabric movement to entice purchases. Infinite white background keeps focus on the garment. Hip-height angle ideal for displaying fabric drape.",
    modelNotes: "Best settings: 9:16, 10-15 seconds, 1080p",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "A perfect sphere of liquid mercury sitting on a mirror surface, slowly deforming under an invisible force into a cube shape, then morphing back to a sphere, reflections shifting with each transformation, seamless loop-ready motion, ASMR-satisfying aesthetic, macro lens extreme close-up, clean minimalist background",
    tags: ["Social Media Viral"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Looping transformation videos perform exceptionally well on social media. The 'seamless loop-ready motion' instruction ensures the ending matches the beginning, crucial for continuous loops. Highly engaging and shareable.",
    modelNotes: "Best settings: 1:1 or 9:16, 6-8 seconds, 1080p",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "The Eiffel Tower reimagined as if it were made entirely of growing crystal formations, glowing from within with ethereal blue light, time-lapse of crystals spreading and growing across the structure, Parisian sunset in the background, magical realism style, drone shot slowly orbiting the tower",
    tags: ["Social Media Viral"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "'What if' scenarios are highly shareable. The Eiffel Tower's lattice structure reinforces the crystalline growth pattern, making it visually compelling. Effective from the first or second generation.",
    modelNotes: "Best settings: 9:16, 10-15 seconds, 1080p",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "Split-screen transition: left side shows a plain coffee mug on a desk, right side reveals the same mug transforming into an ornate golden chalice with jewels, dramatic before-and-after reveal with a satisfying swipe transition, clean studio lighting on both sides, viral transformation trend style",
    tags: ["Social Media Viral"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Before-and-after content performs well algorithmically. Split-screen layout immediately grabs attention. Results can be impressive when the sliding transition hits correctly.",
    modelNotes: "Best settings: 9:16, 6-8 seconds, 1080p",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "A tiny detailed city built inside a glass jar, with miniature cars driving on roads and tiny lights in buildings turning on as day transitions to night, tilt-shift photography effect creating toy-like aesthetic, warm cozy lighting, gentle time-lapse, whimsical and enchanting mood, macro lens perspective",
    tags: ["Social Media Viral"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Miniature worlds have universal appeal. The day-to-night transition adds a narrative element. Tilt-shift effect enhances the toy-size scale, creating a delightful and crafted feel.",
    modelNotes: "Best settings: 9:16, 12-15 seconds, 1080p",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "Two streams of luminescent paint colliding in zero gravity, one electric blue and one molten gold, creating complex fractal patterns as they merge and separate, suspended droplets catching light like stars, extreme slow motion, abstract experimental art film, dark background making colors pop, mesmerizing and meditative",
    tags: ["Creative & Experimental"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Abstract content is culturally agnostic. Complementary vivid colors (electric blue and molten gold) create stunning frames. Useful for background footage for presentations or music tracks.",
    modelNotes: "Best settings: 1:1, 8-10 seconds, 1080p",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "A person walking through a doorway and emerging into an impossible M.C. Escher-inspired landscape where staircases lead in every direction including upside-down, gravity shifting with each step, dreamlike floating dust particles catching shafts of light, ethereal and disorienting, Christopher Nolan's Inception meets Studio Ghibli, smooth steady tracking shot following the walker",
    tags: ["Creative & Experimental"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Reference stacking (Escher, Inception, Ghibli) provides a rich pool of DNA for the model. Results are surreal and eye-catching, with a solid success rate for complex requests.",
    modelNotes: "Best settings: 16:9, 12-15 seconds, 1080p",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "A silhouette of a singer performing on a stage that extends into infinite darkness, colorful volumetric light beams cutting through artificial fog from behind, each lyric note creating visible sound waves rippling through the air as colored light, concert photography perspective from the crowd, Beyonce music video production value, dramatic and powerful energy",
    tags: ["Creative & Experimental"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Volumetric lighting and fog consistently create high-production-value, dramatic shots. Produces arena concert vibes without physical assets. 'Visible sound waves' add an experimental visual element.",
    modelNotes: "Best settings: 16:9 or 9:16, 10-15 seconds, 1080p",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "A multi-shot sequence of a knight in silver armor. Shot 1: Wide shot as he enters a dark cave with a torch. Shot 2: Close-up of his nervous eyes. Shot 3: He draws his sword, which glows blue. Low-angle tracking shot, 2K resolution. Sound of crackling fire and echoing footsteps.",
    tags: ["Cinematic Storytelling"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Seedance 2.0 handles multi-shot narrative logic well, maintaining character consistency across shots. Specific shot descriptions and audio cues enhance storytelling.",
    modelNotes: "Focus on textures for 2K resolution. Native audio engine triggered by sound adjectives.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "A three-shot sequence of a detective in a rainy futuristic city. Shot 1: Bird’s-eye view of neon streets. Shot 2: The detective lights a cigarette under a flickering light. Shot 3: He looks at a holographic photo. 2K sharpness, anamorphic lens flare. Sound of falling rain and distant sirens.",
    tags: ["Cinematic Storytelling"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Effective use of multi-shot sequence to build a narrative. Specific visual details like 'anamorphic lens flare' and atmospheric sounds create a strong cinematic mood.",
    modelNotes: "Focus on textures for 2K resolution. Native audio engine triggered by sound adjectives.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "A sequence of a Victorian tailor at work. Shot 1: Macro shot of a needle piercing silk. Shot 2: The tailor’s face in profile, focused expression. Shot 3: He hangs the finished dress. Natural sunlight, 2K textures. Sound of fabric rustling and scissors snipping.",
    tags: ["Cinematic Storytelling"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed shot descriptions guide the AI to create a coherent story. Focus on textures and natural lighting enhances realism. Specific audio cues add to the immersive experience.",
    modelNotes: "Focus on textures for 2K resolution. Native audio engine triggered by sound adjectives.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "Close-up of a wagyu steak hitting a hot cast-iron skillet. You can see the fat rendering and bubbles of oil. 2K resolution, shallow depth of field. Sound of loud, aggressive sizzling.",
    tags: ["Hyper-Realism"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Focus on textures and specific actions ('fat rendering', 'bubbles of oil') leverages Seedance 2.0's ability to render details. Specific sound descriptions enhance realism.",
    modelNotes: "The ByteDance AI video model loves details like skin pores, wood grain, and liquid. Use specific sound adjectives.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "Slow-motion shot of cold milk being poured into black coffee. The white and brown liquids swirl in 2K detail. Sound of the liquid splashing and the glass clinking.",
    tags: ["Hyper-Realism"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Emphasizes liquid dynamics and detailed textures. Slow-motion enhances the visual appeal. Specific sound effects ('splashing', 'clinking') create an immersive experience.",
    modelNotes: "The ByteDance AI video model loves details like skin pores, wood grain, and liquid. Use specific sound adjectives.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "Extreme close-up of an old man’s face as he laughs. Every wrinkle moves naturally. Cinematic 3-point lighting, 2K resolution. Sound of a deep, gravelly laugh.",
    tags: ["Hyper-Realism"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Focus on natural movement of wrinkles and cinematic lighting enhances realism. Specific audio description ('deep, gravelly laugh') adds depth to the character.",
    modelNotes: "The ByteDance AI video model loves details like skin pores, wood grain, and liquid. Use specific sound adjectives.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "Macro shot of a human eye with a digital iris. Tiny circuits move inside the pupil. 2K resolution, neon blue glow. Sound of a faint digital hum.",
    tags: ["Hyper-Realism"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Combines hyper-realistic detail with a futuristic element. Macro shot emphasizes intricate details. Specific lighting ('neon blue glow') and sound ('faint digital hum') create a unique aesthetic.",
    modelNotes: "The ByteDance AI video model loves details like skin pores, wood grain, and liquid. Use specific sound adjectives.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "A red rally car racing through a forest. It hits a puddle, and water sprays toward the camera. 2K resolution, shaky-cam effect. Sound of a high-RPM engine and splashing water.",
    tags: ["Action and Physics"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Seedance 2.0 excels at rendering physics, especially collisions and speed. Describing the 'water sprays' and 'shaky-cam effect' enhances the dynamic feel. Specific audio cues ('high-RPM engine', 'splashing water') add realism.",
    modelNotes: "Seedance 2.0 wins on weight in physics simulations. Describe friction and specific movements. Use specific sound adjectives.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "A tower of colorful glass blocks being hit by a bowling ball. The blocks scatter with realistic gravity. 2K resolution, high-speed camera style. Sound of a heavy thud and glass clinking.",
    tags: ["Action and Physics"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Demonstrates Seedance 2.0's ability to handle realistic gravity and scattering. 'High-speed camera style' enhances the impact. Specific sound effects ('heavy thud', 'glass clinking') contribute to the immersive experience.",
    modelNotes: "Seedance 2.0 wins on weight in physics simulations. Describe friction and specific movements. Use specific sound adjectives.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "A basketball player jumping for a dunk. The jersey ripples in the wind. The camera follows the player from the ground up. 2K resolution, cinematic lighting. Sound of sneakers squeaking on wood and the rim rattling.",
    tags: ["Action and Physics"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Captures dynamic sports motion with realistic details like 'jersey ripples'. Cinematic lighting and specific camera movement ('follows the player from the ground up') enhance the visual. Accurate sound effects ('sneakers squeaking', 'rim rattling') add authenticity.",
    modelNotes: "Seedance 2.0 wins on weight in physics simulations. Describe friction and specific movements. Use specific sound adjectives.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "A surfer riding a massive 20-foot wave. The spray of the ocean is captured in 2K detail. Sound of a roaring ocean and the board cutting through water.",
    tags: ["Action and Physics"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Highlights Seedance 2.0's capability to render detailed water effects and large-scale natural phenomena. High resolution and specific sound descriptions ('roaring ocean', 'board cutting through water') create a powerful scene.",
    modelNotes: "Seedance 2.0 wins on weight in physics simulations. Describe friction and specific movements. Use specific sound adjectives.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "These are the opening and closing frames of a tavern martial arts fight scene. Based on these two scenes, please generate a smooth sequence of a woman in black fighting several assassins. Use storyboarding techniques and switch between different perspectives to give the entire footage a more rhythmic and cinematic feel.",
    tags: ["Cinematic"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Utilizes storyboarding and multi-perspective shots for a dynamic fight scene. Focus on smooth transitions and cinematic rhythm. Effective for complex action sequences.",
    modelNotes: "Seedance 2.0 excels at following chronological instructions and multi-shot narratives. Use the [00-05s] structure for precise timelines.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "Style: Hollywood Professional Racing Movie (Le Mans style), cinematic night, rain, high-stakes sport. Duration: 15s. [00–05s] Shot 1: The Veteran (Interior / Close-up) Rain lashes the windshield of a high-tech race car on a track. The veteran driver (in helmet) looks over, calm and focused. Dashboard lights reflect on his visor. Dialogue Cue: He gives a subtle nod and mouths, ‘Let’s go.’ [05–10s] Shot 2: The Challenger (Interior / Close-up) Cut to the rival car next to him. The younger driver grips the wheel tightly, breathing heavily. Eyes wide with adrenaline. Dialogue Cue: He whispers ‘Focus’ to himself. [10–15s] Shot 3: The Green Light (Wide Action) The starting lights turn green. Both cars accelerate in perfect sync on the wet asphalt. Water sprays into the camera lens. Motion blur stretches the stadium lights into long streaks of color.",
    tags: ["Cinematic"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed chronological instructions with specific shot breakdowns and dialogue cues guide the AI effectively. Strong stylistic references ('Le Mans style') and atmospheric details ('rain lashes') create a high-impact cinematic sequence.",
    modelNotes: "Seedance 2.0 excels at following chronological instructions and multi-shot narratives. Use the [00-05s] structure for precise timelines.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "Cinematic action movie feel, continuous long take. A female warrior in a black high-tech tactical bodysuit stands in the center of an abandoned industrial factory. The camera follows her in a smooth tracking shot. She delivers a sharp roundhouse kick that sends a zombie flying, then transitions seamlessly into precise one-handed handgun fire, muzzle flash lighting the dark environment.",
    tags: ["Cinematic"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Emphasizes continuous long take and smooth tracking shot for cinematic feel. Detailed action sequence with visual effects ('muzzle flash lighting') creates a dynamic scene.",
    modelNotes: "Seedance 2.0 excels at following chronological instructions and multi-shot narratives. Use the [00-05s] structure for precise timelines.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "A woman in her 40s sits alone at a kitchen table at 3 AM, hands wrapped around a cold coffee mug. Harsh overhead light, shadows under her eyes. She stares at a photograph on the table. The camera slowly pushes in. Her expression shifts from blank to grief. No music. Audio: Refrigerator hum, distant traffic, a single sob.",
    tags: ["Cinematic", "Drama"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Specific time (3 AM) + physical detail (cold coffee) + emotional progression + minimal audio creates powerful dramatic moment.",
    modelNotes: "Seedance 2.0's physics simulation handles subtle human micro-expressions. 'No music' instruction is critical for dramatic scenes.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "A bartender's hands expertly muddle fresh mint leaves in a crystal glass, then pour sparkling water over ice, creating a cascade of bubbles. Close-up macro shot. Slow motion at the pour. Warm amber bar lighting. The finished mojito is garnished with a lime wheel. Premium cocktail bar aesthetic. Audio: Ice clinking, fizzing bubbles.",
    tags: ["Commercial", "Food & Beverage"],
    quality: 1.0,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Process-focused (muddling to finished drink) + macro slow motion + specific audio creates satisfying beverage commercial.",
    modelNotes: "Seedance 2.0's physics simulation is exceptional for liquid and bubble dynamics. Slow motion at pour moment is a reliable technique.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "Abstract music video sequence: geometric shapes in neon pink, electric blue, and gold morph and dance in sync with an imagined beat. The shapes transition from 2D to 3D, casting dramatic shadows. Camera rotates 360 degrees around the central composition. Dark background. Hypnotic, rhythmic movement. Electronic music aesthetic.",
    tags: ["Music Video", "Abstract"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "2D-to-3D transition + color specification + 360-degree camera + rhythmic movement creates dynamic abstract music video content.",
    modelNotes: "Seedance 2.0 handles abstract geometric animation well. 360-degree camera rotation is a reliable dynamic movement technique.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "Shot 1: Extreme close-up of a wolf's amber eye reflecting a winter forest. Cut to: Medium shot of the wolf standing alert on a snow-covered ridge at dawn, breath visible in cold air. Cut to: Wide shot revealing a pack of five wolves moving through deep snow in single file, pine forest behind them. Audio: Wind, distant howl, crunching snow.",
    tags: ["Nature", "Wildlife"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Multi-shot structure (extreme close-up to wide) + breath visibility + pack behavior creates cinematic wildlife documentary.",
    modelNotes: "Seedance 2.0's physics simulation handles breath condensation and snow dynamics authentically. Multi-shot cuts use 'Cut to:' syntax.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "A team of diverse professionals in a modern open-plan office collaborating around a large screen. Energy is positive and focused. Natural light from floor-to-ceiling windows. Camera starts wide showing the full team, then slowly pushes in to a medium shot of two colleagues sharing a moment of discovery. Corporate brand video aesthetic. Audio: Soft ambient office sounds, subtle uplifting background music.",
    tags: ["Brand", "Corporate"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Diversity specification + camera movement from wide to medium + emotional moment (discovery) creates authentic corporate brand content.",
    modelNotes: "Seedance 2.0 handles group dynamics and multi-person scenes well. Camera push-in to intimate moment is a reliable brand video technique.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "seedance-2.0",
    prompt: "Using @Image1 as the spaceship design reference and @Video1 for the explosion style, create: A massive battle cruiser emerges from hyperspace above an alien planet. Energy weapons fire in both directions. The ship takes a critical hit, hull breaching with explosive decompression. Camera executes a dramatic barrel roll around the ship. Cinematic VFX quality. Audio: Deep bass rumble, energy weapon sounds, explosion.",
    tags: ["Sci-Fi", "Action"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "@reference system for design consistency + specific physics event (decompression) + barrel roll camera creates VFX-quality sci-fi action.",
    modelNotes: "Seedance 2.0's @reference system is essential for consistent sci-fi design. Explosive decompression triggers accurate physics simulation.",
    rating: 5,
  },
];
