export const researchVeo31Prompts = [
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Crane shot starting low on a lone hiker and ascending high above, revealing they are standing on the edge of a colossal, mist-filled canyon at sunrise, epic fantasy style, awe-inspiring, soft morning light.",
    tags: ["Landscape", "Cinematic", "Fantasy"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Uses specific camera movement (crane shot) and detailed environmental descriptions to create an epic, awe-inspiring scene with soft morning light.",
    modelNotes: "Demonstrates effective use of cinematography and context for grand scenes.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Close-up with very shallow depth of field, a young woman's face, looking out a bus window at the passing city lights with her reflection faintly visible on the glass, inside a bus at night during a rainstorm, melancholic mood with cool blue tones, moody, cinematic.",
    tags: ["Portrait", "Cinematic"],
    quality: 0.8,
    source: "research_2",
    domain: "photography",
    whyItWorks: "Focuses on composition (close-up, shallow depth of field) and mood (melancholic, cool blue tones) to create an intimate, cinematic shot.",
    modelNotes: "Highlights the model's ability to handle lens effects and emotional ambiance.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Medium shot, a tired corporate worker, rubbing his temples in exhaustion, in front of a bulky 1980s computer in a cluttered office late at night. The scene is lit by the harsh fluorescent overhead lights and the green glow of the monochrome monitor. Retro aesthetic, shot as if on 1980s color film, slightly grainy.",
    tags: ["Corporate", "Retro"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Follows the 5-part formula ([Cinematography] + [Subject] + [Action] + [Context] + [Style & Ambiance]) with specific details on setting, lighting, and retro aesthetic.",
    modelNotes: "Good example of the structured prompt formula for consistent results.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "The camera performs a smooth 180-degree arc shot, starting with the front-facing view of the singer and circling around her to seamlessly end on the POV shot from behind her on stage. The singer sings \"when you look me in the eyes, I can see a million stars.\"",
    tags: ["Music Video", "Cinematic"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Utilizes precise camera movement for a dynamic transition and integrates dialogue/lyrics for synchronized audio, demonstrating the 'first and last frame' workflow.",
    modelNotes: "Excellent for dynamic transitions and audio synchronization.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Using the provided images for the detective, the woman, and the office setting, create a medium shot of the detective behind his desk. He looks up at the woman and says in a weary voice, \"Of all the offices in this town, you had to walk into mine.\"",
    tags: ["Film Noir", "Dialogue"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Uses reference images for character consistency and includes dialogue with specific tone, suitable for narrative scenes.",
    modelNotes: "Demonstrates 'ingredients to video' for consistent characters and dialogue.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Using the provided images for the detective, the woman, and the office setting, create a shot focusing on the woman. A slight, mysterious smile plays on her lips as she replies, \"You were highly recommended.\"",
    tags: ["Film Noir", "Dialogue"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Continues character consistency with reference images and focuses on character expression and dialogue.",
    modelNotes: "Good for multi-shot scenes with consistent characters.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "[00:00-00:02] Medium shot from behind a young female explorer with a leather satchel and messy brown hair in a ponytail, as she pushes aside a large jungle vine to reveal a hidden path.\n[00:02-00:04] Reverse shot of the explorer's freckled face, her expression filled with awe as she gazes upon ancient, moss-covered ruins in the background. SFX: The rustle of dense leaves, distant exotic bird calls.\n[00:04-00:06] Tracking shot following the explorer as she steps into the clearing and runs her hand over the intricate carvings on a crumbling stone wall. Emotion: Wonder and reverence.\n[00:06-00:08] Wide, high-angle crane shot, revealing the lone explorer standing small in the center of the vast, forgotten temple complex, half-swallowed by the jungle. SFX: A swelling, gentle orchestral score begins to play.",
    tags: ["Adventure", "Cinematic"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Uses timestamp prompting for a multi-shot sequence, building a narrative arc with varied camera work, sound effects, and emotional cues.",
    modelNotes: "Exemplifies advanced timestamp prompting for complex narratives.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Medium shot of a tired office worker rubbing his temples at his desk in a cluttered 1980s office late at night. The scene is lit by harsh fluorescent overhead lights and the green glow of a monochrome monitor. Retro aesthetic, shot as if on 1980s color film, slightly grainy.",
    tags: ["Commercial", "Product"],
    quality: 0.8,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Clear definition of camera framing, subject, action, setting, and style, providing all necessary details for Veo 3.1.",
    modelNotes: "Follows the 5-element prompt formula for consistent control.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Crane shot starting low on a lone hiker standing at the edge of a massive canyon and ascending high above to reveal they are standing on the edge of a colossal, mist-filled canyon at sunrise. Epic fantasy style, awe-inspiring scale, soft morning light washing over the landscape. Audio: Gentle wind ambience building into a swelling orchestral score as the camera rises.",
    tags: ["Cinematic", "Landscape", "Fantasy"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Combines specific camera movement, detailed setting, mood, and synchronized audio to create an epic and awe-inspiring scene.",
    modelNotes: "Demonstrates advanced camera movement and audio integration.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Close-up of a woman taking her first sip of coffee on a small balcony overlooking a quiet city street. She's wrapped in a soft sweater, morning light grazing her face. Steam rises gently from the mug. Her shoulders drop slightly as the warmth hits. TV commercial style.",
    tags: ["Commercial", "Lifestyle"],
    quality: 0.8,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Focuses on close-up composition, sensory details (steam, warmth), and a specific style (TV commercial) to evoke a feeling.",
    modelNotes: "Good for emotional intimacy and commercial aesthetics.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "A sleek smartwatch sits on a rugged rock near the edge of a mountain cliff. The camera begins close, then pulls back in a smooth, continuous drone-style shot. As it rises, a vast alpine landscape unfolds—jagged peaks, mist rolling through the valley, and golden sunrise light washing over everything. Cinematic and epic, emphasizing the contrast between modern technology and untamed nature.",
    tags: ["Product", "Cinematic", "Landscape"],
    quality: 1.0,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Combines product focus with cinematic landscape, using smooth drone-style camera movement and emphasizing contrast for an epic feel.",
    modelNotes: "Highlights the model's ability to handle complex camera movements and detailed scene descriptions.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Low-angle medium shot frames a boxer from below as he bounces in place before a match, lit by harsh overhead fluorescents. Sweat glistens on his jawline and neck, catching the cold light. His breath is slow and controlled, his shoulders rolling with each inhale. Huge crowd visible in background. Gritty, cinematic realism.",
    tags: ["Sports", "Gritty", "Cinematic"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Uses low-angle shot for power, detailed subject description (sweat, breath), and specific lighting (harsh fluorescents) to create a gritty, realistic sports scene.",
    modelNotes: "Effective for conveying power and realism through camera angles and details.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Medium shot of a woman in her 30s reading a book at a sunlit Parisian café, warm natural light streaming through tall windows. She looks up from her book and smiles slightly, noticing someone off-camera. Relaxed morning atmosphere, contemporary lifestyle photography. Audio: Gentle café ambience—quiet conversation, espresso machine hiss, light jazz in background.",
    tags: ["Commercial", "Lifestyle"],
    quality: 0.8,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Creates a relaxed atmosphere with warm natural light, subtle action, and detailed ambient audio.",
    modelNotes: "Good for text-to-video (T2V) for concept exploration and rapid prototyping.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "The mountain logo on the tote bag subtly animates, with clean lines tracing the peaks from base to summit. The camera slowly zooms in, focusing on the logo movement. Audio: A gentle whooshing sound as the lines animate, followed by a soft, satisfying click.",
    tags: ["Product", "Commercial"],
    quality: 0.8,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Animates a specific element (logo) with subtle camera movement and synchronized sound effects, ideal for product showcases.",
    modelNotes: "Demonstrates Image-to-Video (I2V) for animating static frames.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "The camera performs a smooth 180-degree arc shot, starting with the front-facing view of the singer and circling around her to seamlessly end on the POV shot from behind her on stage. As the camera moves, the singer opens her eyes and turns slightly. The lighting shifts from dramatic spotlight to bright, energetic stage wash. She sings 'when you look me in the eyes, I can see a million stars.' Audio: Her voice carries throughout with increasing crowd energy as the camera reveals the audience.",
    tags: ["Music Video", "Cinematic"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Provides a detailed camera path, describes visual changes (lighting shift), and integrates dialogue and evolving audio to create a seamless and emotional transition.",
    modelNotes: "Excellent for Start/End Frame (S/E) for controlled transitions and complex audio.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "[00:00-00:02] Medium shot from behind a young explorer as she pushes aside a large jungle vine to reveal a hidden path, her leather satchel visible, messy brown ponytail.\n[00:02-00:04] Reverse shot of the explorer's freckled face, expression filled with awe as she gazes upon ancient moss-covered ruins in the background. SFX: Dense leaves rustling, distant exotic bird calls.\n[00:04-00:06] Tracking shot following the explorer as she steps into the clearing and runs her hand over intricate carvings on a crumbling stone wall. Emotion: Wonder and reverence.\n[00:06-00:08] Wide high-angle crane shot revealing the lone explorer standing small in the center of the vast forgotten temple complex, half-swallowed by jungle. Audio: Gentle orchestral score begins to play.",
    tags: ["Adventure", "Cinematic"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Uses timestamp prompting to create a multi-shot narrative with evolving camera angles, sound effects, and emotional progression.",
    modelNotes: "Ideal for multi-shot sequences with precise cinematic pacing.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Medium shot of a detective in his 40s with short gray hair, rectangular silver glasses, wearing rumpled brown suit. He sits behind his desk in a dimly lit office with venetian blind shadows across his face. Film noir aesthetic. He looks up as someone enters. Audio: Ceiling fan creaking, distant street noise.",
    tags: ["Film Noir", "Character Study"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed character description, specific setting and lighting (film noir, venetian blind shadows), and ambient audio create a strong mood.",
    modelNotes: "Good for establishing character and atmosphere with consistent elements.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Close-up of the same detective with short gray hair and rectangular silver glasses, now shown in profile as he lights a cigarette. The flame briefly illuminates his weathered face. Same dimly lit office, same film noir aesthetic. Audio: Lighter click, slow exhale.",
    tags: ["Film Noir", "Character Study"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Maintains character consistency with repeated details, uses close-up for intimacy, and adds specific sound effects for realism.",
    modelNotes: "Demonstrates character consistency across shots using reference images and text.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Wide shot of the detective with short gray hair and rectangular silver glasses standing at his rain-streaked office window, silhouetted against neon signs outside. He holds a drink, looking out at the city. Film noir with strong backlighting. Audio: Rain pattering on window, distant jazz from neighboring building.",
    tags: ["Film Noir", "Character Study"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Continues character consistency, uses wide shot for context, strong backlighting for dramatic effect, and detailed ambient audio.",
    modelNotes: "Effective for showing character in different contexts while maintaining consistency.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Close-up of a woman's face looking out a bus window at passing city lights, her reflection faintly visible on the glass. Inside a bus at night during a rainstorm. Very shallow depth of field with bokeh from exterior lights. Melancholic mood with cool blue tones. Soft side lighting from window creates gentle shadows on her face. Moody, cinematic.",
    tags: ["Portrait", "Cinematic"],
    quality: 0.8,
    source: "research_2",
    domain: "photography",
    whyItWorks: "Detailed description of lighting, mood, and composition to create an emotional and cinematic portrait.",
    modelNotes: "Emphasizes control over light sources, quality, direction, and color.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "On a matte black tabletop, a ceramic pour-over coffee dripper in glossy white steams gently. Slow dolly-in, macro detail on condensation. Three-point lighting with soft rim light, minimal reflections. High-contrast, modern commercial look. Ambient café hush and subtle kettle pour. She says, 'Meet our morning ritual.' No subtitles.",
    tags: ["Product", "Commercial"],
    quality: 1.0,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Tight subject focus, controlled lighting, slow camera movement, and integrated voiceover create a polished commercial feel.",
    modelNotes: "Excellent for product hero shots, leveraging Veo's adherence and native ambience.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Handheld tracking shot through a sunlit city alley at golden hour. Shallow depth of field; flares and dust motes. Warm amber grade, soft film grain. Footsteps and distant traffic wash; a muted indie guitar chord. No dialogue. No subtitles.",
    tags: ["Cinematic", "Cityscape"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Clear time of day, camera motion, and sound design create a believable urban atmosphere.",
    modelNotes: "Good for lyrical motion and atmospheric B-roll.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Medium close-up of a friendly founder in a bright studio with plants. Soft key light, gentle bounce, clean white backdrop accents. Static camera on tripod. She says, 'Welcome—here’s what we’re building.' Light room tone and soft piano notes. No subtitles.",
    tags: ["Corporate", "Interview"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Simple composition, clear lighting, and short dialogue make for a professional brand introduction.",
    modelNotes: "Effective for talking-head style videos with controlled ambience.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "A clean animated chalkboard shows a simple solar eclipse diagram: Sun, Moon, Earth labeled. Smooth push-in as arrows animate to show movement. Flat, high-contrast classroom style with white lines on dark green. Soft chalk scratch and classroom ambience. Voice says, 'An eclipse happens when the Moon blocks the Sun.' No subtitles.",
    tags: ["Educational", "Animation"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Diagrammatic clarity, animated elements, and short narration are well-suited for educational content.",
    modelNotes: "Leverages Veo's native audio for explainer videos.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Runway medium-wide of a model in a flowing linen suit, cream on cream. Slow tracking left. High-key studio light, soft shadows. Fabric rustle and faint catwalk crowd murmur. She says, 'Effortless for spring.' No subtitles.",
    tags: ["Fashion", "Lookbook"],
    quality: 0.8,
    source: "research_2",
    domain: "photography",
    whyItWorks: "Captures movement, fabric texture, and ambient crowd sounds to convey a fashion context.",
    modelNotes: "Good for showcasing movement and texture in fashion lookbooks.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Extreme close-up of a cast-iron pan as butter foams and a steak sears. Macro steam, micro bubbles. Overhead practical light; warm grade. Sizzle, soft kitchen clatter, no dialogue. No subtitles.",
    tags: ["Food", "ASMR"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Tight macro shot with detailed sound design (sizzle, clatter) creates a realistic ASMR experience.",
    modelNotes: "Excellent for micro-detail and sensory experiences.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Wide aerial sweep over terraced hills at sunrise. Mist drift, golden light. Smooth drone-style motion. Distant birds and morning insects. No dialogue. No subtitles.",
    tags: ["Travel", "Landscape"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Clear landscape, time of day, and motion guide the composition and color for a sense of place.",
    modelNotes: "Effective for travel postcards and drone-style sweeps.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Sideline medium shot as a soccer ball hits the net in slow motion; net ripples crisply. Cool stadium lights, shallow DOF. Crowd swell, thump of ball, whistle in distance. No subtitles.",
    tags: ["Sports", "Slow Motion"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Focuses on a single decisive action in slow motion with iconic sounds for kinetic energy.",
    modelNotes: "Good for capturing sports micro-moments with impactful audio.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Macro time-slice of a desert cactus flower opening as sunlight sweeps across. Cinematic macro lens, shallow DOF, pastel color palette. Soft wind and a faint synth pad. No dialogue. No subtitles.",
    tags: ["Nature", "Science"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Specific subject, lens, and color mood, combined with subtle audio, create a poetic science visualization.",
    modelNotes: "Effective for nature macros and time-slice effects.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Over-the-shoulder shot of a designer at a minimal desk; monitor glow reflects in glasses. Neutral key light, cool grade. Quiet office ambience and subtle keyboard taps. She says, 'Prototype ready.' No subtitles.",
    tags: ["Corporate", "Tech"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Clean blocking, specific lighting, and subtle audio cues create a professional B2B feel.",
    modelNotes: "Good for tech workspaces and corporate settings.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Abstract close-up of soft light sweeping over brushed metal. The light reveals a simple geometric logo etched into the surface. Minimalist, high-contrast studio look. Sub-bass whoosh and subtle sparkle chime. No dialogue. No subtitles.",
    tags: ["Branding", "Abstract"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Describes motion and material with abstract elements and specific sound design for a brand intro.",
    modelNotes: "Effective for logo stings and abstract branding visuals.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Fast three-beat montage: 1) close-up button press; 2) medium shot product in use; 3) wide shot satisfied user. Crisp snap sound for each beat, then a short swell. High-key lighting, modern color grade. She says, 'Done.' No subtitles.",
    tags: ["Social Media", "Montage"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Explicit beat structure and sound cues help pace a quick montage for social media.",
    modelNotes: "Good for rhythmic audio and quick cuts for social hooks.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Intimate close-up of a young adult at a rain-streaked window, soft backlight shaping silhouette. Slow push-in. Gentle piano and rain ambience. He whispers, 'I’m ready.' No subtitles.",
    tags: ["Drama", "Character Study"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Strong lighting, restrained voiceover, and ambient sounds create an emotional and intimate character moment.",
    modelNotes: "Effective for emotional beats and story tone.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Medium handheld shot of a person pointing up and nodding in a bright living room. Natural light, playful vibe. Upbeat clap beat and room tone. No dialogue. No subtitles.",
    tags: ["Social Media", "Meme"],
    quality: 0.6,
    source: "research_2",
    domain: "general",
    whyItWorks: "Keeps the frame clean for post-production text and sets an upbeat tone with audio.",
    modelNotes: "Useful for meme/trend formats where text is added later.",
    rating: 3,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Overhead top-down of hands assembling a simple origami crane on a clean white desk. Even softbox lighting, high-contrast paper edges. Paper rustle ASMR. Voice says, 'Fold to center, then flip.' No subtitles.",
    tags: ["Tutorial", "How-to"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Top-down clarity, crisp details, and short instruction line make it suitable for tutorials.",
    modelNotes: "Good for step-by-step instructions and ASMR details.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Wide crowd shot at a tech conference as lights sweep the stage. Slow pan. Warm concert lighting with haze. Audience cheer, sub-bass thump. No dialogue. No subtitles.",
    tags: ["Event", "Recap"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Distinct lighting, motion, and crowd sounds convey a live event atmosphere.",
    modelNotes: "Effective for event recaps and live vibes.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Slow dolly through a minimalist living room with floor-to-ceiling windows. Morning sun casting long, soft shadows across oak floors; clean white walls. Quiet interior ambience. No dialogue. No subtitles.",
    tags: ["Architectural Visualization", "Interior Design"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Clear materials, light direction, and motion create a refined architectural visualization.",
    modelNotes: "Good for CG-like polish and detailed interior scenes.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Close-up visualization of a simple water molecule model rotating in a dark studio. Cool blue rim light and subtle volumetric haze. Soft synth bed and a faint ‘ping’ as it completes a turn. Voice says, ‘H2O—simple, powerful.’ No subtitles.",
    tags: ["Science Visualization", "Abstract"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Single subject, controlled lighting, and restrained voiceover effectively convey a scientific concept.",
    modelNotes: "Useful for STEM shorts and abstract visualizations.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Animate this still image: a vintage poster of a cyclist on a coastal road. Add gentle paper texture flutter, subtle shadow movement, and a slow parallax dolly-in. Warm retro grade. Seaside wind and distant gulls. No dialogue. No subtitles.",
    tags: ["Image-to-Video", "Retro"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Specifies micro-motions and ambience to animate a still image while preserving its aesthetic.",
    modelNotes: "Demonstrates Image-to-Video capabilities for stylized breathing shots.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Macro close-up of a honeybee landing on a lavender flower in slow motion, wings still visible as a blur, golden afternoon light, pollen visible on its legs. Documentary style, BBC Earth aesthetic. Audio: Soft buzzing fades in, gentle breeze through lavender field.",
    tags: ["Nature", "Documentary"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Macro detail + slow motion + specific lighting + documentary style reference creates a professional nature film feel.",
    modelNotes: "Veo 3.1 handles macro and slow motion exceptionally well. BBC Earth reference triggers high production quality.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Slow-motion tracking shot of a model in a flowing white silk dress walking through a field of tall golden wheat at magic hour. The fabric billows dramatically as she moves. Camera tracks alongside at eye level. Warm amber light, lens flare, Vogue editorial aesthetic.",
    tags: ["Fashion", "Editorial"],
    quality: 1.0,
    source: "research_2",
    domain: "photography",
    whyItWorks: "Slow motion + tracking shot + specific fabric behavior + magic hour lighting creates editorial-quality fashion content.",
    modelNotes: "Specifying fabric behavior (billows, flows) helps Veo 3.1 generate accurate cloth physics.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "Slow push-in on an old Victorian mansion at the end of a fog-covered lane. Dead trees frame the shot. A single light flickers in an upstairs window. The camera moves imperceptibly slow, building dread. No music. Audio: Wind through bare branches, distant owl, creaking wood.",
    tags: ["Horror", "Atmospheric"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Imperceptibly slow camera movement + atmospheric audio design + no music creates psychological tension.",
    modelNotes: "Veo 3.1 responds well to 'no music' and specific ambient sound instructions for horror atmosphere.",
    rating: 4,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "[00:00-00:03] Extreme close-up of a glowing blue eye, cybernetic iris dilating rapidly. SFX: Electronic hum, rapid data processing sounds.\n[00:03-00:06] Pull back to reveal a humanoid android in a dark server room, surrounded by cascading holographic data streams. She raises her hand and the data swirls around her fingers.\n[00:06-00:09] Wide shot: she turns to face the camera, expression neutral but intense. The room behind her erupts in blue light. Audio: Orchestral swell.",
    tags: ["Sci-Fi", "Action"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Timestamp prompting with escalating scale (extreme close-up to wide) creates cinematic reveal structure.",
    modelNotes: "Timestamp format [00:00-00:03] is Veo 3.1's native multi-shot syntax for precise pacing control.",
    rating: 5,
  },
  {
    category: "video",
    targetModel: "higgsfield-veo-3.1",
    prompt: "360-degree product rotation of a luxury leather handbag on a white marble surface. Soft studio lighting with subtle shadows. The bag slowly rotates to reveal all angles. Clean white background. High-end fashion brand aesthetic. No text, no people. Audio: Subtle ambient tone.",
    tags: ["E-commerce", "Product"],
    quality: 0.8,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "360-degree rotation + specific surface material + clean background creates professional product showcase.",
    modelNotes: "Veo 3.1 handles product rotation well. Specifying 'no text, no people' prevents unwanted elements.",
    rating: 4,
  },
];
