export const researchNanaBananaProPrompts = [
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "A high resolution biometric ID photograph of the person in the input image, preserving the exact facial structure, identity, and key features.\n\nThe final image size is exactly 35 x 45 millimeters at 300 DPI (approximately 413 x 531 pixels). The aspect ratio is exactly 7:9 in a vertical portrait orientation, not cropped to 1:1 or 4:3.\n\nThe head height from chin to crown occupies about 70 to 80 percent of the total image height, with around 3 to 5 millimeters of space between the top of the head and the upper edge of the frame.\n\nThe subject is perfectly centered in the frame, shown from the top of the shoulders to just above the head. The person faces the camera directly with a perfectly frontal view: head straight, no tilt or rotation. Eyes are fully open and looking directly into the camera. Expression is neutral, mouth closed, no visible teeth, no exaggerated smile. Both ears and both sides of the face are clearly visible.\n\nThe subject is wearing a simple, plain, dark top (for example a dark crew neck t shirt or a simple collared shirt) with no logos, text, or distracting patterns. No accessories that obscure the face: no sunglasses, no hats, no bulky jewelry. Glasses are allowed only if they are thin framed, non reflective, and do not cast shadows or glare over the eyes.\n\nThe background is a clean, solid light neutral color, such as light gray or off white, with no texture, patterns, or gradients. Lighting is soft, even, and diffused across the entire face, minimizing shadows under the eyes, nose, and chin. No strong highlights, no color casts, and no visible shadows on the background.\n\nShot with a 50mm or 85mm lens at around f/5.6 to ensure full facial sharpness. The entire face, ears, and hairline are in crisp focus while the background remains smooth and unobtrusive. Skin texture looks natural and realistic, with true to life skin tones.\n\nColor grading is minimal and compliant with biometric standards: no filters, no stylized color grading, no exaggerated contrast or saturation. The overall look is clean, clinical, and suitable for official biometric passport and ID photo requirements.",
    tags: ["Utility/Professional"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description of subject, action, location, composition, and style.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "Render an 8K ultrarealistic close shot of a woman (face characteristics 100% same as uploaded image) with windswept black hair partially covering one eye. A sharp diagonal natural light beam illuminates her elevated gaze, showcasing her light irises, high cheekbones, and glossy lips. Deep shadows envelop the rest of her face and the environment, creating a dark, cinematic, editorial mood.",
    tags: ["Portrait/Creative"],
    quality: 0.8,
    source: "research_2",
    domain: "photography",
    whyItWorks: "Detailed description of subject, action, location, composition, and style.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "Create a 9-image Instagram feed for this product in the same aesthetic. Use different locations, angles, and compositions, incorporating people, animals, nature, and various environments while maintaining a cohesive visual style.",
    tags: ["Product/E-commerce"],
    quality: 0.8,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Detailed description of subject, action, location, composition, and style.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "A professional, high-resolution profile photo, maintaining the exact facial structure, identity, and key features of the person in the input image. The subject is framed from the chest up, with ample headroom. The person looks directly at the camera. They are styled for a professional photo studio shoot, wearing a premium smart casual blazer in a subtle charcoal gray. The background is a solid '#562226' neutral studio color. Shot from a high angle with bright and airy soft, diffused studio lighting, gently illuminating the face and creating a subtle catchlight in the eyes, conveying a sense of clarity. Captured on an 85mm f/1.8 lens with a shallow depth of field, exquisite focus on the eyes, and beautiful, soft bokeh. Observe crisp detail on the fabric texture of the blazer, individual strands of hair, and natural, realistic skin texture. The atmosphere exudes confidence, professionalism, and approachability. Clean and bright cinematic color grading with subtle warmth and balanced tones, ensuring a polished and contemporary feel.",
    tags: ["Utility/Professional"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description of subject, action, location, composition, and style.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "{\n  \"image_generation_prompt\": {\n    \"subject\": {\n      \"type\": \"Young woman\",\n      \"hair\": \"Long, silky blonde hair, straight with slight wave, center part, cascading over shoulders\",\n      \"facial_features\": {\n        \"expression\": \"Pouty lips, alluring gaze, soft makeup\",\n        \"eyes\": \"Light colored, defined with eyeliner\"\n      },\n      \"body_type\": \"Slender, fit physique\"\n    },\n    \"attire\": {\n      \"headwear\": \"Large, dark brown faux fur trapper hat (ushanka style) with ear flaps\",\n      \"clothing\": \"Tight-fitting black sleeveless top or bodysuit with a scoop neckline\"\n    },\n    \"accessories\": [\n      \"Gold chain bracelet with clover motifs (Van Cleef & Arpels Alhambra style) on right wrist\",\n      \"Delicate necklace\",\n      \"Manicure with light polish\"\n    ],\n    \"pose_and_action\": {\n      \"type\": \"Mirror selfie\",\n      \"arms\": \"Right arm raised horizontally across the chest with hand framing the chin; Left arm raised holding the camera\",\n      \"framing\": \"Upper body shot\"\n    },\n    \"technical_details\": {\n      \"camera_prop\": \"White compact digital point-and-shoot camera held in hand\",\n      \"lighting\": \"Harsh, direct camera flash creating a bright lens flare and strong highlights\",\n      \"aesthetic\": \"Y2K aesthetics, vintage digital camera vibe, flash photography, candid social media style\",\n      \"background\": \"Neutral, plain beige or off-white wall, slightly shadowed\"\n    }\n  }\n}",
    tags: ["Portrait/Creative"],
    quality: 0.8,
    source: "research_2",
    domain: "photography",
    whyItWorks: "Detailed description of subject, action, location, composition, and style.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "Create an editorial photoreal 3x3 storyboard contact sheet for a high end beauty e commerce ad featuring only the following products: {{product_main}} and {{product_secondary}}\n\nBackground {{background}}.  \nLighting  {{lighting}}.  \n\ngenerate as one evenly spaced 3x3 grid.  \n\n{{panels}}",
    tags: ["Product/E-commerce"],
    quality: 0.8,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Detailed description of subject, action, location, composition, and style.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "Present a clear, 45° top-down isometric miniature 3D cartoon scene of [CITY], featuring its most iconic landmarks and architectural elements. Use soft, refined textures with realistic PBR materials and gentle, lifelike lighting and shadows. Integrate the current weather conditions directly into the city environment to create an immersive atmospheric mood.\nUse a clean, minimalistic composition with a soft, solid-colored background.\n\nAt the top-center, place the title \"[CITY]\" in large bold text, a prominent weather icon beneath it, then the date (small text) and temperature (medium text). All text must be centered with consistent spacing, and may subtly overlap the tops of the buildings.",
    tags: ["Creative/Abstract"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed description of subject, action, location, composition, and style.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "{\n  \"style\": {\n    \"type\": \"hyperrealistic caricature\",\n    \"lighting\": \"soft studio lighting\",\n    \"mood\": \"serious, dramatic\",\n    \"details\": \"exaggerated facial proportions, smooth skin texture, painterly realism\"\n  },\n  \"subject\": {\n    \"type\": \"older man\",\n    \"features\": {\n      \"hair\": \"light blond, voluminous, swept to the side with dramatic flow\",\n      \"face\": \"large exaggerated cheeks and chin, deep frown lines, pronounced brows, slightly drooping eyelids\",\n      \"expression\": \"stern, pouting, serious\"\n    },\n    \"clothing\": {\n      \"outfit\": \"dark formal suit\",\n      \"shirt\": \"light-colored dress shirt\",\n      \"tie\": \"light blue textured tie\"\n    },\n    \"pose\": \"straight posture, facing forward\"\n  },\n  \"background\": {\n    \"type\": \"plain dark gradient\",\n    \"atmosphere\": \"studio portrait, minimalistic\"\n  },\n  \"camera\": {\n    \"angle\": \"straight-on\",\n    \"depth_of_field\": \"shallow, soft background\",\n    \"focus\": \"sharp on face\"\n  }\n}",
    tags: ["Portrait/Creative"],
    quality: 0.8,
    source: "research_2",
    domain: "photography",
    whyItWorks: "Detailed description of subject, action, location, composition, and style.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "Build me a store in the theme and style of {argument name=\"theme_en\" default=\"Thanksgiving Charlie Brown\"}.",
    tags: ["E-commerce"],
    quality: 0.8,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "A succinct prompt to build a store interface themed in the style of Thanksgiving Charlie Brown, suitable as a web storefront design.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "I want to design the landing page for a new {argument name=\"product_type_en\" default=\"AI game\"}. We want it to look futuristic and use as many animations as possible.",
    tags: ["Gaming"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "An English prompt used inside a Claude Code skill that asks Gemini 3 Pro to design a futuristic, animation-rich landing page for a new AI game.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "Help me build a hello world page.\n\nHelp me build a hello world page with {argument name=\"style_en\" default=\"Linear\"} style.\n\nHelp me build a hello world page with {argument name=\"style_en\" default=\"Linear\"} style.",
    tags: ["Web Development"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Three simple prompts for Gemini 3.0 that show how adding style and imagery—specifically a Linear-style design and an image prompt—changes the quality of a generated hello world page.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "Design a 3D product experience page for a luxury wristwatch.\n**Target users:** wealthy customers, watch enthusiasts, and business people aged 30–50.\n**Brand tone:** Luxury × Tech (a modern, sophisticated high-end feel).\nScroll experience (5 sections):\nHero section – the wristwatch slowly appears from darkness into light while rotating. Implement holographic effects and Fresnel reflections with custom shaders.\nDetail zoom – close-up of the dial. Use GLSL to achieve metallic reflections, parallax mapping, and real-time glossiness.\nMechanism breakdown – the watch disassembles and the internal movement floats in space. Use a displacement shader for an energy-field effect and add glow effects to each part.\nMaterial experience – switch between different material variations. Express metalness, glass refraction, and the matte texture of titanium with PBR shaders in a physically based way.\nEnding – the watch reassembles, with an abstract gradient mesh background made with a custom shader. Apply post-processing such as bloom and depth of field.\n**Tech stack:** Next.js 15 + Three.js + React Three Fiber + GLSL (custom shaders) + react-postprocessing + Lenis.\nShader requirements:\nFresnel reflection shader (rim-light effect)\nPBR material shader (roughness, metallic, AO)\nHolographic shader (iridescent interference effect)\nDisplacement shader (waving and distortion effects)\nCustom background shader (gradient noise)\nPost-process: Bloom, ChromaticAberration, DepthOfField, Vignette.\nPlease propose specific numerical values for:\nScroll range of each section (from, to)\nCamera position (x, y, z) and rotation (x, y, z) for each section\nGLSL shader uniform values (e.g., uFresnelPower, uDisplacementStrength, uGradientColor1, uGradientColor2)\nPost-processing effect parameters (e.g., bloom intensity, DoF focusDistance, vignette darkness)",
    tags: ["Product Design"],
    quality: 0.8,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "A long, detailed Japanese prompt for designing a luxury 3D product experience web page for high-end watches, using Next.js, Three.js, React Three Fiber, GLSL, and specific scroll sections and shader requirements.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "I want to build a web page with a custom color palette, layout, and font.\n\nI want to build a web page with a custom color palette, layout, and font.\n\nI want to build a web page with a custom color palette, layout, and font.",
    tags: ["Web Development"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "A prompt for creating a web page with a custom color palette, layout, and font, demonstrating Gemini 3.0's ability to interpret and apply specific design instructions.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "I want to build a Zelda-themed web page.",
    tags: ["Gaming"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "A prompt to create a Zelda-themed web page, showcasing Gemini 3.0's ability to generate a design based on a well-known visual style.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "I want to generate a set of icons with a specified style and color palette.",
    tags: ["Graphic Design"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "A prompt to generate a set of icons with a specified style and color palette, demonstrating Gemini 3.0's ability to create consistent visual assets.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "I want to create a voxel-art style image.",
    tags: ["Art/Voxel"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "A prompt to create a voxel-art style image, showcasing Gemini 3.0's ability to generate images in a specific artistic style.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "I want to generate a dashboard for visualizing cryptocurrency data.",
    tags: ["Data Visualization"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "A prompt to generate a dashboard for visualizing cryptocurrency data, demonstrating Gemini 3.0's ability to create data-driven interfaces.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "I want to create a 3D scene with a specified object and lighting.",
    tags: ["General"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "A prompt to create a 3D scene with a specified object and lighting, demonstrating Gemini 3.0's ability to generate 3D graphics.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "I want to create a 3D animation with a specified object and motion path.",
    tags: ["General"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "A prompt to create a 3D animation with a specified object and motion path, demonstrating Gemini 3.0's ability to generate animated 3D graphics.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "I want to create a 3D game with specified characters, environment, and gameplay mechanics.",
    tags: ["General"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "A prompt to create a 3D game with specified characters, environment, and gameplay mechanics, demonstrating Gemini 3.0's ability to generate complex interactive experiences.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "I want to create a 3D simulation of a physical system with specified parameters and initial conditions.",
    tags: ["General"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "A prompt to create a 3D simulation of a physical system with specified parameters and initial conditions, demonstrating Gemini 3.0's ability to generate scientific visualizations.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "I want to create a 3D model of a building from architectural plans.",
    tags: ["General"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "A prompt to create a 3D model of a building from architectural plans, demonstrating Gemini 3.0's ability to work with technical drawings.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "I want to create a 3D model of a human from a photograph.",
    tags: ["General"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "A prompt to create a 3D model of a human from a photograph, demonstrating Gemini 3.0's ability to work with image data.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "I want to create a 3D model of a car from a sketch.",
    tags: ["General"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "A prompt to create a 3D model of a car from a sketch, demonstrating Gemini 3.0's ability to work with hand-drawn images.",
    modelNotes: "",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "A cinematic shot of a lone astronaut standing on a desolate, alien planet. The sky is a swirling vortex of nebulae in shades of deep purple and magenta. Two moons hang in the sky, one casting a soft, ethereal glow. The astronaut, clad in a sleek, futuristic suit, looks out at the vast, unknown landscape. The ground is a cracked, dark terrain, with strange, crystalline formations jutting out. The mood is one of awe and isolation. 16k, sharp focus, f/2.8, Canon EOS R5.",
    tags: ["cinematic"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "This prompt is highly detailed, specifying the subject, setting, mood, and even technical camera settings. This level of detail helps the AI to generate a precise and high-quality image.",
    modelNotes: "Nano Banana Pro excels at interpreting complex scenes and detailed lighting instructions. The mention of specific camera settings seems to enhance the realism.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "A minimalist, professional product shot of a sleek, modern smartwatch. The watch face displays a vibrant, abstract design. The watch is placed on a clean, white background, with a soft, diffused light from the side creating a gentle shadow. The image should be sharp, clean, and ready for an e-commerce website. Shot on a Sony A7R IV, 90mm macro lens, f/8.",
    tags: ["e-commerce"],
    quality: 1.0,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "This prompt is perfect for e-commerce as it clearly defines the product, the desired aesthetic (minimalist, professional), and the background. The technical details guide the AI to create a commercially viable image.",
    modelNotes: "This model is particularly good at creating clean, well-lit product images. It understands the nuances of commercial photography and can produce images that require minimal post-processing.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "A dramatic, black and white portrait of an elderly man with deep wrinkles and a thoughtful expression. The lighting is high-contrast, with one side of his face in shadow. He wears a simple, dark turtleneck sweater. The background is a plain, dark gray. The focus is on his eyes, which convey a sense of wisdom and experience. Hasselblad X1D II 50C, 80mm f/1.9.",
    tags: ["portrait"],
    quality: 1.0,
    source: "research_2",
    domain: "photography",
    whyItWorks: "This prompt uses strong emotional and descriptive words (dramatic, deep wrinkles, thoughtful expression) to guide the AI in creating a powerful portrait. The black and white specification is a key creative choice.",
    modelNotes: "Nano Banana Pro has a remarkable ability to capture and convey human emotion. It also handles monochrome palettes with a high degree of sophistication, creating rich and nuanced black and white images.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "An epic, breathtaking landscape of the Scottish Highlands at sunrise. A thick fog blankets the valleys, with the peaks of the mountains piercing through. The rising sun casts a warm, golden light on the scene. A lone stag stands on a ridge, silhouetted against the sky. The image should be wide-angle, capturing the vastness of the landscape. Fujifilm GFX 100S, 23mm f/4.",
    tags: ["landscape"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "This prompt paints a vivid picture for the AI, using evocative language (epic, breathtaking, thick fog) and specifying the time of day and a key focal point (the lone stag).",
    modelNotes: "This model is excellent at generating atmospheric and realistic landscapes. It is particularly adept at rendering complex weather conditions like fog and the warm light of sunrise.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "A vibrant, abstract explosion of color and light. The image should be a dynamic interplay of swirling, organic shapes and sharp, geometric lines. The color palette is a mix of neon pinks, electric blues, and deep purples. The texture is a combination of smooth, glossy surfaces and rough, grainy elements. The overall feeling is one of energy and movement. 3D render, Octane Render, 4k.",
    tags: ["abstract"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "This prompt gives the AI a lot of creative freedom while still providing clear guidelines on color, shape, and texture. The mention of 3D rendering software (Octane Render) can also influence the style.",
    modelNotes: "Nano Banana Pro can generate stunning abstract images. It is not limited to photorealism and can create unique and imaginative visuals based on abstract concepts.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "A charming, whimsical illustration of a fox reading a book in a cozy, cluttered library. The style is reminiscent of classic children’s book illustrations, with soft colors and a warm, inviting atmosphere. The fox wears a pair of reading glasses and a cozy sweater. The library is filled with books, with a fireplace crackling in the background. Watercolor and ink on textured paper.",
    tags: ["illustration"],
    quality: 1.0,
    source: "research_2",
    domain: "illustration",
    whyItWorks: "This prompt clearly defines the subject, setting, and desired artistic style. The mention of specific media (watercolor and ink on textured paper) is a powerful instruction for the AI.",
    modelNotes: "This model can emulate a wide range of artistic styles, including traditional media like watercolor. It can create charming and detailed illustrations that are perfect for storytelling.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "Professional e-commerce product shot of a navy blue linen blazer displayed on an invisible mannequin (ghost mannequin effect). Clean white background. Soft studio lighting with no harsh shadows. Show front view with lapels, buttons, and pocket details clearly visible. Commercial product photography quality.",
    tags: ["E-commerce", "Apparel"],
    quality: 1.0,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Ghost mannequin specification + clean background + detail visibility instruction creates professional apparel e-commerce imagery.",
    modelNotes: "Nano Banana Pro excels at ghost mannequin/invisible mannequin technique. Clean white background is the optimal e-commerce preset.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "Create a vibrant Instagram-ready promotional image for a summer smoothie brand. A tall glass filled with layered tropical smoothie (mango, pineapple, coconut) with a paper straw and fresh fruit garnish. Shot from a 45-degree angle on a bright turquoise surface. Playful, colorful, Gen Z aesthetic. Include space for text overlay at the top.",
    tags: ["Marketing", "Social Media"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Platform-specific (Instagram) + demographic targeting (Gen Z) + text overlay space instruction creates marketing-ready content.",
    modelNotes: "Nano Banana Pro's multimodal understanding allows platform-specific optimization. 'Space for text overlay' is a useful composition instruction.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "Professional LinkedIn headshot of a confident business professional in their 30s. Clean navy blue blazer, subtle smile, direct eye contact with camera. Soft neutral background (light gray or off-white). Rembrandt lighting setup. Sharp focus on face, slight shoulder blur. Corporate professional aesthetic.",
    tags: ["Portrait", "Professional"],
    quality: 0.8,
    source: "research_2",
    domain: "photography",
    whyItWorks: "Platform-specific (LinkedIn) + lighting technique name (Rembrandt) + professional context creates credible business portrait.",
    modelNotes: "Named lighting techniques (Rembrandt, butterfly, split) give Nano Banana Pro precise lighting control.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "Editorial illustration for a technology magazine article about artificial intelligence. A human hand and a robotic hand reaching toward each other, fingertips almost touching (inspired by Michelangelo's Creation of Adam). Clean, modern graphic style with a limited palette of deep blue, white, and electric teal. Suitable for magazine cover.",
    tags: ["Illustration", "Editorial"],
    quality: 1.0,
    source: "research_2",
    domain: "illustration",
    whyItWorks: "Cultural reference (Michelangelo) + specific color palette + publication context creates conceptually rich editorial illustration.",
    modelNotes: "Nano Banana Pro's reasoning capability allows it to interpret cultural references and translate them into modern visual contexts.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-nano-banana-pro",
    prompt: "Architectural visualization of a modern sustainable home. Curved organic forms, living green roof, large floor-to-ceiling windows. Surrounded by native landscaping. Golden hour lighting. Shot from a low angle looking up. Photorealistic render quality. Architectural photography aesthetic.",
    tags: ["Architecture", "Exterior"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Sustainable architecture keywords + organic forms + golden hour + low angle creates aspirational architectural imagery.",
    modelNotes: "Nano Banana Pro handles architectural visualization with photorealistic quality. Low angle shots emphasize scale and grandeur.",
    rating: 4,
  },
];
