export const researchFluxPrompts = [
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Red fox sitting in tall grass, wildlife documentary photography, misty dawn",
    tags: ["General/Structured Prompt"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Follows the Subject + Action + Style + Context framework, providing a clear and detailed description.",
    modelNotes: "Demonstrates the effectiveness of the core FLUX framework.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Human explorer in futuristic gear walking through cyberpunk forest, dramatic atmospheric lighting, sci-fi fantasy art style, cinematic composition",
    tags: ["Sci-Fi/Fantasy"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Uses natural language and structured descriptions for a complex scene, incorporating visual and atmospheric layers.",
    modelNotes: "Highlights the model's ability to handle imaginative settings.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "An astronaut with a silver spacesuit floating outside the International Space Station, cinematic photography with dramatic lighting, peaceful and awe-inspiring",
    tags: ["Space/Cinematic"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Combines subject, action, style, and context with emotional tone, showcasing enhancement layers.",
    modelNotes: "Good example of using natural language for evocative imagery.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Retro game style detective in old school suit, upper body shot, colorful, futuristic design with vibrant glow",
    tags: ["Retro/Character"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Focuses on character and style, using descriptive adjectives for visual impact.",
    modelNotes: "Demonstrates how to combine different stylistic elements effectively.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "An astronaut with silver spacesuit floating gracefully outside the International Space Station, cinematic photography with dramatic lighting, bathed in golden sunlight, deep blue Earth tones, shallow depth of field, 85mm lens, conveying wonder and achievement",
    tags: ["Enhanced/Cinematic"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Excellent use of enhancement layers, including visual (golden sunlight, deep blue Earth tones), technical (shallow depth of field, 85mm lens), and atmospheric (wonder and achievement) details.",
    modelNotes: "Shows the power of detailed, layered prompts for high-quality results.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Elderly wizard with long white beard and piercing blue eyes, casting a spell, fantasy art style, in a magical forest clearing",
    tags: ["Character-focused"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Follows the character-focused pattern: Detailed character -> Action -> Style -> Context.",
    modelNotes: "Illustrates how to build a prompt step-by-step for character-centric images.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Ancient Greek temple ruins at sunset, golden hour lighting, cinematic photography style, with scattered marble columns",
    tags: ["Context-focused"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Follows the context-focused pattern: Setting -> Atmospheric conditions -> Style -> Technical specs.",
    modelNotes: "Good for generating detailed landscapes and architectural scenes.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Van Gogh painting style with swirling brushstrokes, depicting a modern city street, vibrant blues and yellows, impressionist technique",
    tags: ["Style-focused"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Follows the style-focused pattern: Artistic reference -> Subject -> Context -> Technical execution.",
    modelNotes: "Effective for artistic interpretations and style transfers.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Professional headshot of a business executive, clean white background, studio lighting, 85mm lens, f/1.4, shallow depth of field",
    tags: ["Technical-focused"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Follows the technical-focused pattern: Subject -> Background -> Lighting -> Lens/settings, with precise camera details.",
    modelNotes: "Ideal for generating professional photography with specific technical controls.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Professional headshot, 85mm lens, f/2.8, Rembrandt lighting, corporate setting",
    tags: ["Professional Photography"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Combines advanced photography controls (lens, aperture, lighting style) with context for a highly specific output.",
    modelNotes: "Demonstrates the model's capability for fine-grained control over photographic elements.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Nature documentary capture on Hasselblad X2D 100C with XCD 90V lens at f/4: [Majestic snow-capped mountain peak emerges through swirling morning mist], [golden sunrise light catches crystalline ice formations], creating [ethereal alpenglow effect]. Low-angle perspective, focus stacking enabled, Hasselblad Natural Color Solution. Early dawn atmospheric conditions with layered cloud formations in background.",
    tags: ["Nature Documentary"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Highly specific technical foundation (camera, lens, aperture), active language for the main subject, and detailed environmental storytelling (light interaction, atmospheric conditions). Uses brackets for emphasis.",
    modelNotes: "Flux responds well to active language and understands context and nuance due to T5 and CLIP encoders. High-resolution output on Nebius AI Studio enhances detail.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Vehicle-mounted GoPro HERO12 Black: [Rally car powerslides through forest stage] in Finnish wilderness, [gravel spray creating dramatic patterns] in low autumn sunlight. HDR mode handles extreme contrast between dark forest and bright clearings. Audio capture of engine notes and gravel impacts.",
    tags: ["Dynamic Sports (Rally Racing)"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Specifies camera, active action, environmental details, and technical settings (HDR mode) for dynamic scenes.",
    modelNotes: "Good for action-oriented scenes and capturing dynamic elements.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Studio Ghibli meets Makoto Shinkai aesthetic: [A young witch practices spells] in her floating treehouse observatory, where [magical particles swirl through shafts of dusty sunset light]. Emphasized light bloom, classic cel shading technique, detailed background art with multiple parallax layers. Volumetric god rays, detailed wood grain textures, signature anime floating particles. Reference: Howl's Moving Castle architectural detail mixed with Your Name lighting.",
    tags: ["Animated Magic (Studio Ghibli Style)"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Combines two distinct artistic styles, uses active language, and includes numerous stylistic and technical details (light bloom, cel shading, volumetric god rays, specific references).",
    modelNotes: "Demonstrates Flux's ability to blend styles and interpret detailed artistic instructions.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "iPhone 15 Pro ProRAW capture in Portrait Mode (48MP): [A ballet dancer practices alone] in [an abandoned Detroit theater], dust particles swirling through dramatic light beams. Natural lens flare and cinematic color grading emphasize the contrast between decay and grace. Shot with Morning light, Photographic Styles set to Rich Contrast.",
    tags: ["Modern Smartphone Photography (Ballet)"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Specifies modern camera and mode, detailed subject and context, and advanced photographic effects (lens flare, color grading, lighting).",
    modelNotes: "Shows how to achieve specific photographic looks with modern camera settings.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Spider-verse-inspired animation style: [A street artist creates a massive mural] while [gravity shifts around them], bending the city's perspective. Comic book halftone dots visible in shadows, bold line work, dynamic color palette with purposeful chromatic aberration. Includes Ben-Day dots, ink outlines, and purposeful animation smears. Style of Into the Spider-Verse meets Arcane.",
    tags: ["Street Art / Animation (Spider-Verse Style)"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Combines a strong artistic style reference with dynamic action, unique visual effects (gravity shifts, halftone dots), and specific animation techniques.",
    modelNotes: "Excellent for generating stylized, dynamic, and complex animated scenes.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "GoPro HERO12 Black chest-mounted: [Professional mountain biker hits a massive drop] in Utah's Red Bull Rampage, [red dust exploding around wheels] against piercing blue desert sky. Natural sunlight creating lens flares, extreme wide-angle perspective showing vertical drop below. RAW capture preserves both shadow detail in dust clouds and bright sky. Ultra-realistic motion blur at edges.",
    tags: ["Dynamic Sports (Mountain Biking)"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Specifies camera and mounting, intense action, detailed environmental interaction, and advanced photographic effects (lens flares, wide-angle, RAW capture, motion blur).",
    modelNotes: "Effective for high-energy sports photography with detailed environmental interaction.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Leica M11 with 35mm Summilux-M f/1.4: [Rain-slicked cobblestone street reflects neon signs], while [steam rises from subway grates], creating [film noir atmosphere]. Shot at street level, pushed Tri-X processing simulation, heavy contrast with preserved shadow detail.",
    tags: ["Street Photography (Film Noir)"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Uses specific high-end camera and lens, detailed atmospheric conditions, and strong stylistic elements (film noir, processing simulation, contrast).",
    modelNotes: "Demonstrates fine control over photographic style and mood, suitable for artistic street photography.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "A vibrant orange and pink sunset over a snow-capped mountain range, with soft, wispy clouds reflecting off a calm lake in the foreground.",
    tags: ["Landscape"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Demonstrates the importance of specific details for improved image generation.",
    modelNotes: "FLUX.1 responds best to precise and clear language.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "A majestic mountain peak emerging through swirling morning mist, with golden sunrise light catching the crystalline ice formations.",
    tags: ["Nature"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Uses dynamic and active language to create a sense of movement and drama.",
    modelNotes: "Active language helps FLUX.1 create dynamic and energetic images.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "A hanging glass terrarium featuring a miniature rainforest scene with colorful orchids and tiny waterfalls (foreground). Just beyond the glass, a neon sign reads ‘Rainforest Retreat’ in bright green and yellow letters (middle ground). The rain-soaked glass creates a beautiful distortion, adding a soft glow to the sign's vibrant colors (background).",
    tags: ["Interior/Object"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Clearly defines placement of elements in foreground, middle ground, and background for depth.",
    modelNotes: "FLUX.1 allows defining placement of objects in different layers.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "A single tree standing in the middle of the image. The left half of the tree has bright, vibrant green leaves under a sunny blue sky, while the right half has bare branches covered in frost, with a cold, dark, thunderous sky. On the left, there's lush green grass; on the right, thick snow. The split is sharp, with the transition happening right down the middle of the tree.",
    tags: ["Abstract/Contrasting"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Uses strong contrasting elements to create a visually striking image.",
    modelNotes: "Contrasting colors and aesthetics make images more striking and memorable.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "A landscape where the left side is sunny and bright, with golden fields and a clear blue sky, while the right side is rainy and dark, with storm clouds and wet grass. The transition between the two sides is soft and blended, creating a dreamy effect.",
    tags: ["Landscape"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Describes a soft transition between contrasting elements, affecting mood and visual flow.",
    modelNotes: "The type of transition affects the mood and visual flow of the image.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "A neon sign reading ‘Rainforest Retreat’ visible through a rain-soaked glass window. The glass creates a beautiful distortion, adding a soft glow to the sign's vibrant colors.",
    tags: ["Object/Text"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Uses transparent material to create a visually interesting effect and depth.",
    modelNotes: "FLUX.1 can create images with transparent materials like glass.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "A glass of water on a wooden table, with light reflecting off the surface of the glass. The glass is covered in tiny water droplets, and the table has a rough, textured finish.",
    tags: ["Still Life"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Adds textures and reflections for realism and depth.",
    modelNotes: "Textures and reflections make images more lifelike and engaging.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "A vibrant orange and pink sunset over a snow-capped mountain range, shot on a Canon EOS R5, capturing the vibrant colors and sharp details of the scene.",
    tags: ["Landscape"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Specifies camera type to mimic real-world photography style and quality.",
    modelNotes: "Specifying a camera helps FLUX.1 mimic the style and quality of real-world photography.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "A portrait shot with a 50mm lens, capturing the subject’s face in sharp focus with a softly blurred background.",
    tags: ["Portrait"],
    quality: 0.8,
    source: "research_2",
    domain: "photography",
    whyItWorks: "Uses lens specification to control depth of field and focus.",
    modelNotes: "Lenses control field of view and depth of field.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "A wide-angle shot of a mountain range at sunrise, capturing the expansive landscape with vibrant colors and sharp details.",
    tags: ["Landscape"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Specifies shot type for desired composition and scene capture.",
    modelNotes: "Shot types influence the overall composition.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "A vintage travel poster for Paris. The Eiffel Tower silhouette dominates the center, painted in warm sunset colors. At the top, ‘PARIS’ is written in large, elegant Art Deco font.",
    tags: ["Text Integration"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Clearly describes text content, placement, and style for readable text in images.",
    modelNotes: "FLUX can generate readable text when described clearly.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "close up photo of a 30 year old woman with pixie cut red hair and natural green eyes, looking away from the camera, side profile, high contrast, with a night cityscape in the background",
    tags: ["Character"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Detailed, conversational prompt that uses natural language instead of comma-separated tags.",
    modelNotes: "Natural language prompts work well with Flux.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Style: Classic superhero comic Character: Worried scientist frantically typing on glowing holographic keyboard, face illuminated by blue light showing deep concern Setting: Massive computer server room with sparking circuits and red warning lights flashing on monitors Text: ‘The AI models are corrupting! We need Diffusion Man!’ Mood: Tense, urgent + dramatic blue and red tones",
    tags: ["Comic Strip"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Defines character and maintains consistency across panels for sequential art.",
    modelNotes: "FLUX.2 can create consistent comic panels.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Samsung Galaxy S25 Ultra product advertisement, 'Ultra-strong titanium' headline, 'Shielded in a strong titanium frame, your Galaxy S25 Ultra always stays protected' subtext, close-up of phone edge showing titanium frame, dark gradient background, clean minimalist tech aesthetic, professional product photography",
    tags: ["Typography/Design"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Generates clean typography and product marketing materials.",
    modelNotes: "FLUX.2 excels at typography and design-related prompts.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "a vintage illustration of an apple in color #0047AB with a heart-shaped cutout in the middle, on a white background",
    tags: ["Color Control (HEX)"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Uses HEX color codes for precise color matching.",
    modelNotes: "FLUX.2 supports precise color matching using hex codes.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "A vase on a table in living room, the color of the vase is a gradient, starting with color #02eb3c and finishing with color #edfa3c. The flowers inside the vase have the color #ff0088",
    tags: ["Color Control (Gradient)"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Applies gradients by specifying start and end colors.",
    modelNotes: "FLUX.2 can generate gradients.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Create a vertical infographic about coffee consumption worldwide. Title: ‘Global Coffee Culture’. Include 3 sections with statistics, use icons for each country, color scheme #4A2C2A (brown) and #F5E6D3 (cream). Modern minimalist style with clean typography.",
    tags: ["Infographics"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Generates infographics with clean typography and structured layouts.",
    modelNotes: "FLUX.2 can generate infographics.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Un marché alimentaire dans la campagne normande",
    tags: ["Multi-Language"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Prompting in a native language can produce more culturally authentic results.",
    modelNotes: "FLUX.2 understands multiple languages.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Portrait of a 35-year-old Japanese woman with shoulder-length black hair, wearing a simple white linen shirt, standing in a sunlit Tokyo apartment. Warm morning light through sheer curtains. Shot on Fujifilm GFX 100S with 110mm f/2 lens. Shallow depth of field, soft bokeh. Natural, unposed moment.",
    tags: ["Portrait", "Photorealistic"],
    quality: 1.0,
    source: "research_2",
    domain: "photography",
    whyItWorks: "Specific camera model + lens specs + natural light source + unposed instruction creates authentic photorealistic portrait.",
    modelNotes: "FLUX.2 responds exceptionally to specific camera/lens combinations. Fujifilm cameras trigger characteristic warm, film-like rendering.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "A lone pine tree silhouetted against a dramatic sunset sky over the Scottish Highlands. Layers of purple and orange clouds. Foreground heather in soft focus. Shot on large format 4x5 film camera. Long exposure, slight motion in clouds. Ansel Adams compositional style with color.",
    tags: ["Landscape", "Fine Art"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Large format film reference + Ansel Adams compositional reference + layered atmospheric elements creates fine art landscape.",
    modelNotes: "FLUX.1 Pro Ultra's Raw mode enhances film photography aesthetics. Large format film reference triggers high tonal range.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Luxury watch advertisement style photo. A Submariner-style dive watch resting on wet black volcanic rock, ocean spray in the background. Dramatic overcast sky. Close-up macro shot showing dial details, bezel, and water droplets on crystal. Shot on Canon EOS R5 with 100mm macro lens. High contrast, dramatic lighting.",
    tags: ["Commercial", "Advertising"],
    quality: 1.0,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Advertising style reference + environmental storytelling + macro detail + specific camera creates premium product advertising imagery.",
    modelNotes: "FLUX handles luxury product photography exceptionally. Wet surfaces and water droplets add premium visual texture.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "A vast underground crystal cavern where enormous amethyst formations grow from the floor and ceiling, lit by bioluminescent organisms living within the crystals. A tiny human figure stands at the entrance for scale. Concept art style, painterly, cinematic lighting. Inspired by Roger Dean album artwork.",
    tags: ["Concept Art", "Fantasy"],
    quality: 0.8,
    source: "research_2",
    domain: "general",
    whyItWorks: "Scale contrast (tiny human) + bioluminescence + specific artist reference (Roger Dean) creates immersive concept art.",
    modelNotes: "FLUX.1 dev is optimal for concept art with artist style references. Roger Dean reference triggers organic, surreal fantasy aesthetics.",
    rating: 4,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Black and white street photography in 1960s New York City. A crowded intersection in Manhattan, steam rising from a grate, yellow cabs, people in period clothing rushing past. Shot on Leica M3 with 35mm Summicron lens. High contrast, grain, decisive moment style. Henri Cartier-Bresson influence.",
    tags: ["Street Photography", "Documentary"],
    quality: 1.0,
    source: "research_2",
    domain: "general",
    whyItWorks: "Historical period + specific camera (Leica M3) + master photographer reference (Cartier-Bresson) creates authentic documentary aesthetic.",
    modelNotes: "FLUX handles historical period photography with high accuracy. Leica camera references trigger characteristic documentary style.",
    rating: 5,
  },
  {
    category: "image",
    targetModel: "lovart-flux-2",
    prompt: "Minimalist product photography of a matte black wireless earphone case on a pure white background. Perfect studio lighting with subtle gradient shadow. The case is open, revealing the earphones inside. Shot from a 30-degree overhead angle. Apple product photography aesthetic. Ultra clean, no distractions.",
    tags: ["Product", "Minimalist"],
    quality: 1.0,
    source: "research_2",
    domain: "e-commerce",
    whyItWorks: "Apple product photography reference is the gold standard for minimalist product shots. Specific angle + shadow instruction creates depth.",
    modelNotes: "FLUX.2 Pro handles minimalist product photography with exceptional cleanliness. Apple reference triggers precise, controlled lighting.",
    rating: 5,
  },
];
